### ISSUE TITLE
rfe: alias DPMI memory

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1058]
As was pointed out here:
https://github.com/stsp/dosemu2/pull/1057#issuecomment-601659609
we may need to alias DPMI memory
if we are serious about DPMI-jit (which
IMO would be great to have).
20 years ago there was a limit on sysv
shm, which was by default something
like 32Mb (don't remember exactly, could
be even less), so I just converted DPMI
to anonymous mapping. But these days
we do not use sysv shm, and the limits
are different. By default we have 128Mb
of DPMI mem. Mapping 128Mb of shared
mem on 64bit arches is not a big deal.

**Comment by jschwartzenberg** [comment]
I didn't keep track of the recent improvements. How does this affect performance/compatibility?

**Comment by stsp** [comment]
What exactly?
Bart fixed some compatibility
problems with jit. This ticket is
about fixing a few more w/o
sacrificing the performance.

**Comment by jschwartzenberg** [comment]
Do you know specific software that's affected? Maybe it's also what fixed DN2?

**Comment by stsp** [comment]
It did.

**Comment by bartoldeman** [comment]
I'm not sure if it helps, there are some pros and cons. I doubt it will help performance since page faults are quite rare for DPMI already as code and data are much less often on the same page than in vm86. It may help code clarity a bit though as you now know that LINEAR2UNIX gives a writable address (unless it's VGA)

Another alternative would be a faultless JIT without mprotect. You absolutely need mprotect for JIT vm86 + native DPMI, but for full JIT it could be done completely in software.

**Comment by stsp** [comment]
I just want to find some consistent solution.
Previously, because the faults are rare, I
wanted to just use e_invalidate manually
in a few places. But you want to build them
into a macros, and the macros that are also
used for lowmem, and not only by DPMI
subsystem. If the invalidation cases are
rare, I think this is not the best approach.
Either DPMI-specific macros (len arg to
SEL_ADR_W() + read/write accessors)
or a faultless jit are fine with me, if the
problem is too small to alias the DPMI
mem just for that.

**Comment by stsp** [comment]
Off-topic:
https://www.youtube.com/watch?v=KRLm4mKhUVU
Though I think it is some kind of trolling,
not a real review of dosemu2. :)

**Comment by bartoldeman** [comment]
I don't really want to build it into the macros, ideally I'd let `SEL_ADR_X()` return a `dosaddr_t` and not use any pointers into DOS space, instead use only functions (`read_byte(), memcpy_*` etc, where only dos2linux.c uses LINEAR2UNIX etc. and nowhere else).
The point is really that `e_invalidate` is quick and a no-op if the memory is already unprotected or is aliased, which is >99% of all cases (ie. unprotected) for DPMI memory.
I should probably implement a few counters to see how many exactly :)

**Comment by stsp** [comment]
But read_byte(), memcpy_* and all that -
use aliased pointers normally. If you force
them to always unprotect, then these cases
where unprotect is not needed (because the
protection can stay, not because there was
no protection at all) will became slower.
Perhaps we then need a decision to stop
using aliased space w/o unprotecting first.
But if we can use aliased space w/o unprotecting,
then I suppose coding unprotect into an access
macros is not good.

**Comment by bartoldeman** [comment]
No I don't want to force them to unprotect, that is indeed not good! Just do what `memcpy_2dos` (which takes a dosaddr_t, the aliased pointer is hidden inside the function) does now, ie.
1. Check bitmap, if unprotected, write as usual (alias'ed or not doesn't matter), return
2. If protected then
  a. check via another bitmap if it hits code, if so, invalidate that code
  b. vga memory, call vga functions, return
  c. if aliased lowmem, write to alias, return
  d. if DPMI memory, unprotect and write, return

Now I am arguing that 2.d. is a fairly rare case, and we now catch it with `dosemu_error` if we fail to call `e_invalidate`.

The main issue with the current approach of simply using the pointers into aliased memory and writing directly to them without checking is that you don't catch 2.a. and 2.b.

For 2.a. that can be problematic if you write data over code and the JIT doesn't know the code hasn't been invalidated (a leak most likely); 2.b. is less likely to happen since you don't really want to put filenames into VGA memory but you never know what crazy things DOS programs do..

**Comment by stsp** [comment]
But is also either you hit code or not.
I.e. its not just one case.
The fact that it is treated as one, bothers
me. Unnecessary unprotects.

**Comment by stsp** [comment]
Of course perhaps you mean that
2.d w/o code hit almost never happens?
(insert 2.d after word "but" in my prev
msg)

**Comment by bartoldeman** [comment]
Correct I mean the latter since pages in dpmi progs typically don't share code and data... Of course there is some self modifying code. I'll get some stats later.

**Comment by stsp** [comment]
Maybe you meant the later, but your
patches suggest you had data and code
mixed in. Or was it not the case?

**Comment by bartoldeman** [comment]
Correct there was code and data mixed in, and that faulted about 10 times. That's nothing compared to the 1000s of other faults that happen.. but like I said I'll need more stats, also for the case when dpmi code faults and the cpatch unprotects.

**Comment by stsp** [comment]
So what are you going to do with
linear2unix then? Completely ban?
I think I much rather need to see
the size of the patch for that, than
any fault stats. :)

**Comment by bartoldeman** [comment]
The patch would be enormous indeed :(

I'm warming up more and more to the idea of the fault-less JIT. I experimented a bit more with using the CPatches unconditionally and dosemu boots just as fast as before (or even slightly faster).

For DPMI the case of Causeway is a little extreme since that one indeed mixes code and data on a single page (I checked the source code) and produces ~20,000 page faults, which now means code regeneration, and a delay of 0.8 seconds (about 40 microseconds per fault). That is completely eliminated if this is done in software.

And that's without much optimization on the software checks, there is an interesting blog here:
http://www.emulators.com/docs/nx08_stlb.htm
essentially this technique can be used to implement a cache to quickly check if a 256-byte section of memory is safe to write to, e.g. for dwords it would like:
```
table_index = (addr >> 8) & 0xff; /* this is the hash */
if (((pagetbl[table_index].addr_page ^ (addr + 3)) & 0xFFFF0300) == 0)
    *(uint32_t)(pagetbl[table_index].alias | (addr & 0xff))  = x;
else
    /* expensive way, check for VGA, update pagetbl etc. */
```
where for e.g. address 0x12345678 the addr_page field (if hit) at index 0x56 has the value
0x12345600 if it's writable memory and the value 0x12345600 ^ 0x200 = 0x12345400 if it's not writable. The alias field then contains LINEAR2UNIX(DOSADDR_REL(0x12345600)).

this will take a bit of time to properly implement though but not needing to deal with page faults is tempting.. One would still need to protect code and use the alias for writes for jit+native or jit+kvm though but not for full jit.

**Comment by stsp** [comment]
Yes, the attempt to ban linear2unix
will likely be comparable to mem_base32
macrosifying, which took a few years.
But at least in case of mem_base32
everyone was confident this is the right
thing to do, while removing linear2unix
just for an experiment... not sure.

As for faultless jit - I also fail to see
the logic. If you claim there almost
no faults in dpmi code except for cw
extender, then how would that not
became a pessimization?

OTOH I do not feel like aliasing
the dpmi space is the best and only
approach possible. At least its simple,
so my current thinking is either that
or don't touch. :)

**Comment by stsp** [comment]
So given that cw extender uses code/data
mix (and I really think other "people" doo too,
just not so frequently as in real mode), I
suppose even if you ban linear2unix, you still
can't count on the fact that the fault==code_hit.
In which case you still need an alias.

So it looks like we have 3 possible strategies:
1. alias DPMI space. Optionally ban linear2unix -
leaving it in won't hurt in this case, at least won't
hurt more than it already does.
Pros: simple. consistent with what we have for lowmem.
Cons: wasting 128Mb of shm, which may not be
worth the problem we try to solve.

2. always unprotect, assuming fault==code_hit.
Pros: technically appealing
Cons: pissimization when fault!=code_hit. not
consistent with what we have now for lowmem.
needs to either ban linear2unix (2.a, difficult), or only
ban dpmi-specific variations of it, like SEL_ADR_X()
(2.b, simple).

3. fault-less jit
Pros: portable
Cons: difficult. slow.
I think it is slow because the jit faults in DPMI
should be rare, regardless of whether its a code
hit or not. So you trade the rare faults to increased
logic in generated memory access code.

Now when this all is written out, its much simpler
to think about that.
I think it would be very cool to have 3 just as another
emulation option, for portability. And its not something
that is needed right now.
I also think that implementing 2.b doesn't hurt, as
later one can also implement 1 (or something else!),
and 2.b will take an advantage of it by no longer assuming
fault==code_hit.
What to do with linear2unix in general, can be
decided at any later stage.

So... 2.b? :)

**Comment by bartoldeman** [comment]
I am happy about 2.b. for sure, however do note that SEL_ADR_X is also used for read-addresses and sometimes it uses strcmp on those.
Introducing SEL_ADR_W and then using memcpy_2dos on the write cases would fix that (and we need to invalidate the code if it's writing on top of code, also if page protection is switched off in 3)

However do note that the vast majority of faults come from the JIT itself, within DPMI that code is CPatch'ed and then the Cpatch unprotects the page.

As for 3 it's actually a very simple patch, and it's surprisingly performing (it just fails for Windows because the page faults on the LDT aren't correctly handled any more, same for general DPMI  page faults as tested in test-i386.exe). Sure it adds some cycles for every write but those are snowed under by everything else that happens. But I'm all for doing it optionally, any ideas for a runtime option? `$_cpu_emu = "softmmu"` or `"softJIT"`? (in #564 I proposed to use "JIT" and "simulated" as possible values, but I don't think  I ever got round to that...)

**Comment by stsp** [comment]
> I am happy about 2.b. for sure, however do note that SEL_ADR_X is also
> used for read-addresses and sometimes it uses strcmp on those.

Yes, I think the strategy should be to make
SEL_ADR_X() return dosaddr_t (which you
suggested initially), rather than to introduce
SEL_ADR_W() or alike. I think I am more
and more convincing myself that fully switching
to dosaddr_t is a future-proof move, and
so why not to start from dpmi and get back
to linear2unix sometime later. The reason
is simple: linear2unix (and so SEL_ADR_X()),
even working with aliased space, may leave
you with an unnoticed code hit sooner or later.
But the biggest problem for me with fully
accepting that view, is also simple: you are
safe with KVM or native or vm86. So changing
such a core thing for something that is even
not enabled by default. :( And it will likely give
the slight performance hit to kvm/native/vm86,
and will definitely complicate the code (you
won't be able to use the pointer to the struct
in DOS mem). So I think the good compromise
is to switch DPMI stuff to dosaddr_t and see,
and perhaps not do the same to linear2unix. :)
Which is 2.b.

> However do note that the vast majority of faults come from the JIT itself

You mean, `!InCompiledCode`?
What would that be?

> any ideas for a runtime option?

Perhaps another option, like `$_cpu_jit_mode`?
The problem is, we already have a separate set
of bugs for different simx86 modes. There would
be even more. :)

**Comment by stsp** [comment]
Bart, what about the fault-less sim (not jit)?
That would allow us to work under windows-10.
sigcontext is not properly supported there, so
all that siglongjump() trick doesn't work.

**Comment by bartoldeman** [comment]
That should already work except for Windows 3.x LDT writes and DPMI page faults (fairly uncommon but tested in test-i386.exe).
Basically the write routines in the sim need to be modified to check for those addresses (and a TLB-like structure as explained above would help there too)

**Comment by stsp** [comment]
> That should already work except for Windows 3.x LDT writes and DPMI
> page faults (fairly uncommon but tested in test-i386.exe).

And vgaemu?

The last time we discussed that, you were against such idea:
https://github.com/stsp/dosemu2/pull/149#discussion_r56493644
But I think its time to put that forward, as
in fact dosemu can now (somewhat) work
on windows.

**Comment by stsp** [comment]
Off-topic: I created the dosemu2 organization
at github and invited people there.
I have zero idea what does that mean, just
wanted to see what happens.
You may want to accept or deny the invitation
and I don't know what will change when you do. :)

**Comment by stsp** [comment]
And I also created dosemu2 project.
So we now have repository, organization
and the project... hmm.

**Comment by stsp** [comment]
And now we seem to have new URLs:
instead of github.com/stsp/* it is now
github.com/dosemu2/*
So in particular the dosemu2 repository is now:
`https://github.com/dosemu2/dosemu2`
Oh crap, what have I done...
But it looks like the former URLs work too.
There is some kind of redirect.

**Comment by stsp** [comment]
So I am no longer a project owner,
but just a collaborator. :) How cool.

**Comment by bartoldeman** [comment]
Faultless JIT works with vgaemu and should work with LDTs too, but not page faults, although I have a proof of concept stashed somewhere for that case, after which I returned to the simulator.

As for my former comment from 2016, the "TLB" will revert any slowdowns that I added to the simulator now, a quick test gave it a 99.7% hit rate when booting DOS.

**Comment by stsp** [comment]
> Faultless JIT works with vgaemu and should work with LDTs too, but not page faults,
> although I have a proof of concept stashed somewhere for that case, after which I
> returned to the simulator.

How does faultless jit handle the code self-modifications?
"softtlb" tricks in the compiled code?

> As for my former comment from 2016, the "TLB" will revert any slowdowns that I
> added to the simulator now, a quick test gave it a 99.7% hit rate when booting DOS.

What kind of slowdown have you added to
simulator? A few checks for vga/ldt mem is
not accounted as a slowdown I suppose?

**Comment by bartoldeman** [comment]
> > Faultless JIT works with vgaemu and should work with LDTs too, but not page faults,
> > although I have a proof of concept stashed somewhere for that case, after which I
> > returned to the simulator.
>
> How does faultless jit handle the code self-modifications?
> "softtlb" tricks in the compiled code?

In my faultless JIT experiments, the memory writes call the cpatch routines which check the bitmaps if the affected memory region contains code, and if so invalidate. The "softtlb" just speeds that up.

> What kind of slowdown have you added to
> simulator? A few checks for vga/ldt mem is
> not accounted as a slowdown I suppose?

they cause a slowdown (though as the simulator is slow already you don't see it very well), because every single memory read and write goes through those checks. The checks for VGA and LDT are fairly quick (so buried in the general simulator slowness) but some in  `dpmi_is_valid_range()` are more expensive, and that's especially where the "softtlb" comes in.

**Comment by stsp** [comment]
> In my faultless JIT experiments, the memory writes call the cpatch routines

You mean, all compiled memory writes do that?
Wouldn't that be a very big slow-down?
Yes, you are going to do the same thing for
sim, but sim was slow anyway, and is needed
only for portability. I think jit should either be
uber-fast, or we should move to sim entirely. :)

**Comment by bartoldeman** [comment]
You'd think it's a big slow-down but I didn't notice any difference even without the TLB and just using Cpatch unconditionally for all writes.

**Comment by stsp** [comment]
How many asm instructions the single
store will now have?

**Comment by bartoldeman** [comment]
With the Soft TLB about 10 instructions (something like the asm in http://www.emulators.com/docs/nx08_stlb.htm). Calling CPatch unconditionally, probably closer to 100.

Which is a good reason to keep it optional, so you can benchmark it :)

**Comment by stsp** [comment]
Having it optional means that you still
need to decide what to do with fault-full
jit wrt aliasing. That is, you still need the
technique to invalidate in case of a code
hit, and write in case of data hit (so alias
region or alike).
Having it non-optional reduces the above
to just the code-hit case, and you still need
a check-invalidate, but at least no need for
an alias (which is a clear 2.b).
So really, it doesn't look like it has any
value at all being optional. Non-optional,
it will at least get us rid of the aliasing need.
10 insns seems doable indeed, if the reward
is a no need to add DPMI alias. :)

**Comment by stsp** [comment]
Btw, if you do the same for vm86jit,
then I'll be able to benchmark it very
accurately, as I already have a good
benchmark for that.
If we find it acceptable for vm86jit,
then that will be a big relief?

**Comment by stsp** [comment]
In fact, even the code hit is not always
require the invalidation. For example if
you did linear2unix() and hit the code,
then it is the stalled code, because the
risk of loading real code into mem from
unix side can be only by reading the file
from FS in a redirector, or doing an
XMS/EMS memcpy.
So what do we actually gain from banning
linear2unix or converting SEL_ADR_X()
to dosaddr_t? Do those unnoticed codehits
lead to memory leaks? Likely not, as there
is a GC logic in jit.

So it seems with fault-less jit (as the only
jit) we indeed can leave things as they are
now, use linear2unix, use SEL_ADR_W()
and completely ignore any possible code hits,
allowing GC to remove them later.
Sounds reasonable?

**Comment by stsp** [comment]
Commit 5443b0a1b will then also be
unneeded in its current form. We may
want to use such helpers only in
msdos.c, emm.c, xms.c and mfs.c,
because all other places I think can't
load any code, even if they produce
code hit (not sure about fdpp).

**Comment by bartoldeman** [comment]
Yes that sounds reasonable. It means that copying data into DOS space is generally ok (if it's not vgaemu etc.), on the other hand calling e_invalidate doesn't hurt either, it just means it's not necessary for those cases. I'd like to keep memcpy_2dos invalidating just because it's a worry-free function to use then, the invalidate is a cheap operation even on DPMI once you have a faultless JIT (since it no longer needs to unprotect/invalidate the whole page), and it can then also be used directly by the JIT and the simulator.

**Comment by stsp** [comment]
Ok, but at least then no need for
any further changes, like converting
dpmi to dosaddr_t, which is good
by itself. But how to fix the dpmi=kvm
and vm86=jit, or vice versa? If kvm
will not hit the protection, we are screwed.

**Comment by stsp** [comment]
And if we do faultless vm86jit, then
also native dpmi screwed up!
So it seems, faultless jit can only
work exclusively on dpmi+vm86?

**Comment by bartoldeman** [comment]
I haven't tested vm86 jit + DPMI kvm at all yet, but for vm86 jit + native DPMI, vm86 can run faultless (by using aliased memory), but if native DPMI code writes to low memory, then that memory will still need to be unprotected and invalidated.

I'll submit a PR later today (faultless JIT without soft TLB) that is not to be merged yet but that way you can run your benchmark.

**Comment by stsp** [comment]
> I'd like to keep memcpy_2dos invalidating just because it's a worry-free function to use

But what should I do with fdpp?
It is currently rescued by the use of the
redirector, but its not like fatfs should
be broken. And I don't even know what
public API to offer for that problem.
If I add "invalidate" API to fdpp, people
will ask why I only invalidate in blkdev,
there are many other writes. So there
is simply no consistent API for that.

Can we get to the beginning. :)
I would propose to insert some prologue
to some code nodes, that will just
compare, say, 512 bytes of code with
its backup done upon jitting. If they
match, then the subsequent code nodes
within the same 512 block are safe.
If not - 512 bytes are invalidated.
512 bytes seems to be possible to
compare with a single SSE insn, so
it isn't going to be a big overhead,
plus it will happen relatively rare.
In that case you may still need the
memory write checks in the compiled
code, but they will only care about
hitting theirown  512bytes block,
because if they hit something else,
it will be noticed later wnyway.
So that design seems to be simpler
than the softtlb proposal, and, unless
I miss something, it really solves the
problem, while softtlb design solves
some parts and raises too many
questions in an exchange.

**Comment by stsp** [comment]
> I haven't tested vm86 jit + DPMI kvm at all yet,

You can't, it doesn't work.
KVM hits protection, and game over.

> but if native DPMI code writes to low memory, then that memory will still need
> to be unprotected and invalidated.

This is what we do now.
But in case of a faultless vm86jit,
DPMI can write to lowmem and get
unnoticed. In case of faultless DPMI
jit, kvm can write to lowmem and
hit DPMI code there. This is very
unlikely, so perhaps the combo of
faultless DPMI jit + v86kvm can survive,
but faultless vm86jit will immediately
hit problems.
What do you think about the 512bytes
block checks suggested above? I
really think this solves all and every
problem we have here, but I may be
biased.

**Comment by stsp** [comment]
> where if DPMI writes to lowmem it's noticed the same way as before

But what if DPMI stores some of its code
in lowmem? Yes, very unlikely, but I can
write such test. :)
Also this means we can't have vm86jit
same fault-less, because native DPMi
will write there and that will be unnoticed.

> needing to deal with linked nodes, jumps etc

I think the algorithm can be quite simple:
when jitting, see if the current node is within
the 512 block or not, and if not - add another
one. But see how much the memory writes
can then be optimized. Instead of checking
for dpmi protection or alike, you just check
for one simple condition: if the write is within
the current 512 block or not. 4 instructions. :)

**Comment by stsp** [comment]
> #1086 is a simple faultless JIT

It makes vm86jit fault-less too?
Then what happens when native DPMI
writes to it?

**Comment by bartoldeman** [comment]
If (native) DPMI stores its code in lowmem, then you get a fault, and that lowmem will be unprotected, invalidated etc, as was done before.
Next time vm86 uses code in that same lowmem page it will be re-jitted and protected.
I'll repeat it only eliminates faults from JITted code, not from native code.

**Comment by stsp** [comment]
Ah, cool, I understand now.
I thought fault-less means completely
fault-less. :)
OK, let me benchmark that a bit then.

**Comment by stsp** [comment]
Wait, your log says:
```
no longer mprotect DPMI memory
```
What happens if that DPMI memory appears
in lowmem, i.e. (jit) DPMI put and executed some
code in lowmem? Will it be protected?

**Comment by stsp** [comment]
OK, I checked with my zx_emul test.
devel:
```
real	0m20,525s
user	0m18,439s
sys	0m0,498s
```
your patch:
```
real	0m34,080s
user	0m32,255s
sys	0m0,570s
```

And the music on that test is audibly much slower.
But the numbers do not matter much, as I
first would like to understand what problem
do you solve. What does it give us to avoid
faults only from compiled code? Some speed-up?
It surely solves none of the architectural
problems we have here, right?
And its still unclear what if DPMI jit puts the
code to lowmem. Will it be protected?

**Comment by bartoldeman** [comment]
In full mode (DPMI JIT) it'll write to aliased memory and never fault.

What I mean with "no longer mprotect DPMI memory" I mean all memory above 1M + 64k that is not aliased.

**Comment by stsp** [comment]
> In full mode (DPMI JIT) it'll write to aliased memory and never fault.

DPMI jit doesn't inevitably mean "full".
You can still have vm86kvm at the same
time, and I was wondering what if vm86kvm
writes to the dpmi-jitted mem that happened
to be in lowmem.
But I guess you answered that already: it will
be protected because it is below 1Mb, regardless
of dpmi-jit that put it there.
Anyway, I think calling cpatch per every memory
write is inherently flawed, both wrt performance
and wrt problems that it can solve (none).

**Comment by bartoldeman** [comment]
I have never even thought to combine vm86kvm with dpmi-jit, but well, interesting combination.
But vm86kvm should fault and then invalidate since the memory is below 1M+64k.

Yes Cpatch for every write is too slow, and that's where a TLB helps. As for problems it solves, it ensures that the address obtained by LINEAR2UNIX is always writable since it's either aliased low mem or unprotected high mem. In full jit mode it also eliminates the slowdowns through excessive page faults with the causeway dos extender that combines code and data on a single page.

**Comment by stsp** [comment]
> ensures that the address obtained by LINEAR2UNIX is always writable since it's
> either aliased low mem or unprotected high mem.

With manual invalidations in msdos/xms/ems/mfs
and access macros, and fsck on fdpp? But this
doesn't move us an inch forward, as this all is
already there (with access macros invalidation
even being redundant).

> In full jit mode it also eliminates the slowdowns through
> excessive page faults with the causeway dos extender
> that combines code and data on a single page.

Excessive, or just one, that calls cpatch?
I think we need to discuss other approaches. :)

**Comment by stsp** [comment]
> With manual invalidations in msdos/xms/ems/mfs
> and access macros, and fsck on fdpp?

JFYI I did a surgery on fdpp and confined
most of its memory accesses. They now go
through manual code invalidation.
Whether right or wrong, but at least its better
than nothing at all.
So now I can discuss the fault-less jit approach
in a much less biased fashion.

So if I understand the idea correctly, you
change 1 fault that calls cpatch, to 0 faults,
and call cpatch always. This probably only
helps if the page is being re-jitted too frequently,
so the cpatches are constantly undone?

**Comment by stsp** [comment]
So a quick recap of what was intended,
and what was done on that subject.
So vgaemu has 2 modes:
a. normal mode. We protect clean pages
and unprotect on fault
b. mode-x. always protected, instremu is used
to simulate.

What was intended:
1. native execution.
- In a (normal mode) keep things unprotected and
use polling. Done in vgacpy branch.
- In b (mode-x) use fault-less jit to generate
replacements for faulted code. Not done.
2. KVM.
- In a use PML. See #198 
- In b use the same as for 1.b
3. JIT
- In a use always protected alias and cpatch.
Done in dpmibase branch, but is unstable. :(
Instead vgacpy branch have to use polling
similar to 1.a.
- In b use cpatch, as is now.

So not done are 1.b, 2.a and 3.a.

**Comment by stsp** [comment]
DPMI memory is now fully aliased.
Also even though we dont dynamically
dispatch jit yet, we use sim.
So this is solved.
