### ISSUE TITLE
Installing dosemu2 over DOSEMU?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1187]
A friend who had the old DOSEMU installed on a test system tried to install the new dosemu2 by following the instructions in the wiki, and then couldn't use either the old system or the new system.

Is there any advice out there for people who want to replace the old system with the new one? 

EDIT: I see there is such advice: https://github.com/dosemu2/dosemu2/issues/994

**Comment by stsp** [comment]
Yes, $_hdimage comments have examples
for a compatibility setup.
Not sure what your problem is.
You friend have very likely used some
pre-alpha of dosemu2, like pre8.
Those could indeed spoil the existing
setup!
Current code is very careful with
user's data, so you can always revert.
See if ~/.dosemu/drives contains the
.lnk files, and remove them if they are
there.

**Comment by stsp** [comment]
I probably should remove all pre-alphas.
But then... nothing is left. :(

**Comment by andrewbird** [comment]
I'm really surprised that dosemu2 doesn't work with a standard dosemu drive c etc. I suppose that if a user has a dosemurc then some options may have changed, but I think we'd probably need some more info on what exactly doesn't work rather than to guess what the cause might be.

**Comment by emendelson** [comment]
I'll ask my friend to post details here. He was following the instructions I wrote in the wiki, so he was using the latest code. Other than that, I don't have any details.
