### ISSUE TITLE
ECM's DPMI tests

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1273]
@ecm-pushbx I see you have some DPMI [tests](https://hg.ulukai.org/ecm/dpmitest/file/tip) available in the public domain, I'm thinking it might be nice to add them to the Dosemu2 test suite. Firstly, are you happy about that, I'll only add them if you are? If so, I have a few questions
1. Do you see value in those tests for Dosemu2?
2. I'm not really familiar with Nasm, can you tell me what command line is required to build them?
3. Have you already tested on Dosemu2 and was it successful? If so, I can find out what output to check for, otherwise I might need some hints?

BTW is your [Bitbucket](https://bitbucket.org/ecm/workspace/repositories?visibility=all) unused now, as there seems to be very little on there?

**Comment by andrewbird** [comment]
@stsp I added some [tests](https://github.com/andrewbird/dosemu2/commit/4df493ff90033b0c9040ddf0b3cf6f144fefed8e) for DPMI (Japheth) and EMS (Borland), can you recommend some DOS tool for XMS tests tool?

**Comment by stsp** [comment]
[prot.cpp.txt](https://github.com/dosemu2/dosemu2/files/5176348/prot.cpp.txt)
[dpmi16.h.txt](https://github.com/dosemu2/dosemu2/files/5176350/dpmi16.h.txt)

I've found the DPMI test I wrote 20
years ago for dosemu1. It had to be
run multiple times to make sure the
results printed, are always the same.
It seems to be not the case right now
though...

**Comment by andrewbird** [comment]
Which compiler does that use?

**Comment by stsp** [comment]
bc3.1.
Oh well, never mind. :)

**Comment by ecm-pushbx** [comment]
> @ecm-pushbx I see you have some DPMI tests available in the public domain, I'm thinking it might be nice to add them to the Dosemu2 test suite. Firstly, are you happy about that, I'll only add them if you are?

Yes, I'd be happy to have you use the tests. That's what they are there for. By the way, they are based on the tests that were included in lDebug / FreeDOS Debug at some point. (Besides [my lDebug repo](https://hg.ulukai.org/ecm/ldebug) which I believe never had the tests included, I also uploaded the entire history of [FreeDOS Debug to a repo](https://hg.ulukai.org/ecm/fddebug). You can check the example files at various points in time there.)

> If so, I have a few questions

>    Do you see value in those tests for Dosemu2?

Sure!

>    I'm not really familiar with Nasm, can you tell me what command line is required to build them?

Generally `nasm -f bin -o NAME.com NAME.asm -I path/to/lmacros/` where the include path should be set to point to the lmacros1/2/3 files [from my lmacros collection](https://hg.ulukai.org/ecm/lmacros). (Of the four tests there currently, only dpmialoc uses the macro collection but it doesn't do any harm to add the include directory anyway. Plus, if you ever update the tests then some of the others that are not yet using the macro collection may start to do so.)

>    Have you already tested on Dosemu2 and was it successful? If so, I can find out what output to check for, otherwise I might need some hints?

I just tested them on my desktop (AMD64 Debian 11) and here is the output:

```
dpmitest$ dosemu --version
dosemu2-2.0pre8-20200606-1904-gd042de76b
Revision: 5603
dpmitest$ for file in *.asm; do nasm -f bin -I [...]/lmacros/ -o "${file%.asm}".com "$file"; echo ===; dosemu -K "$PWD" -E "${file%.asm}.com" -dumb -quiet; done
===
About to Execute : dpmialoc.com
Protected mode breakpoint at 0221h.
32-bit code segment breakpoint at 0233h.
Return from child process at 0403h.

Welcome in 32-bit protected mode.
DPMI allocation at 02121000h.
DPMI allocation entrypoint at 00EFh:00000000h.
Real mode procedure called at 00EFh:00000044h.
DPMI allocation exit at 00EFh:0000006Ch.
Hello from DPMI memory section!
Calling real mode procedure which called callback successful.
Child process terminated okay, back in real mode.
===
About to Execute : dpmimini.com
Protected mode breakpoint at 015Ah.
32-bit code segment breakpoint at 016Ch.

Welcome in 32-bit protected mode.
===
About to Execute : dpmims.com
Protected mode breakpoint at 015Eh.

Welcome in protected mode.
Mode-switched to real mode.
In protected mode again.
===
About to Execute : dpmipsp.com
Protected mode breakpoint at 0221h.
32-bit code segment breakpoint at 0233h.
Real mode procedure called at 0275h.
Return from child process at 02FCh.

Welcome in 32-bit protected mode.
Calling real mode procedure which called callback successful.
Child process terminated okay, back in real mode.
```

I just checked that these are all the expected success messages (meaning, all messages other than those for errors). A non-zero return code from any of the tests indicates an error. However, not all errors are reflected in the code, so a zero return code does not indicate success with certainty. It is probably best if you check for the exact message matches (other than the selectors and offsets of the displayed addresses) and update the expected messages if the tests change.

> BTW is your Bitbucket unused now, as there seems to be very little on there?

Yes, it is, because bitbucket decided to delete all support for hg / Mercurial repos and also locked out writes and eventually deleted all existing such repos. As you already know I migrated my repos to hg.ulukai.org (my partner's server running hgweb).

**Comment by stsp** [comment]
> Yes, it is, because bitbucket decided to delete all support for hg / Mercurial repos and also locked out
> writes and eventually deleted all existing such repos.

Just for the record:
https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket

Wow!
They really did.
And people blame me/dosemu2
for not being backward-compatible... :)

**Comment by andrewbird** [comment]
@ecm-pushbx thanks for the info, I'll see about getting them into Dosemu's Travis test soon!
