### ISSUE TITLE
Support passthrough of physical VGA cards

### ISSUE THREAD

**Issue by volkertb** [dosemu2/dosemu2#1301]
On host systems that support hardware-assisted virtualization and have an IOMMU, KVM supports the passthrough of graphics cards from the host to a guest VM.

For a more genuine retro "experience" (native text mode, 70Hz refresh, better performance than software emulation, etc), it would be great if we could add an older PCI VGA card (with proper native register-level DOS compatibility and proper VESA VBE 2.0 or 3.0 LFB support) as a secondary card and have dosemu2 use that card exclusively through passthrough.

How feasible would this be to implement?

**Comment by jschwartzenberg** [comment]
Passthrough of VGA should work already, but it's been a while since I tried and I understood from @stsp you have to disable KMS for it. Also for win31 you'll have to patch the SVGA driver (and can't use the Trident ones that work with the VGA emulation). A second separate card might not be supported yet.

**Comment by stsp** [comment]
This already works for primary cards.
Just not enabled in lp builds, as no
one needed that functionality for decades,
and also you need to disable modeset
and have the root privs to do that.
Secondary card pass-through is difficult
to implement because you need to
reprogram bridges so that they pass
the legacy vga io ports to that card.
If you had some other os with the driver
for that specific card or that uses only
vbe, then you only need to remap the
pci rom so thats quite simple.
But full vga access that dosemu needs,
is very difficult to get from the secondary
card.

**Comment by stsp** [comment]
This already works for primary cards.
Just not enabled in lp builds, as no
one needed that functionality for decades,
and also you need to disable modeset
and have the root privs to do that.
Secondary card pass-through is difficult
to implement because you need to
reprogram bridges so that they pass
the legacy vga io ports to that card.
If you had some other os with the driver
for that specific card or that uses only
vbe, then you only need to remap the
pci rom so thats quite simple.
But full vga access that dosemu needs,
is very difficult to get from the secondary
card.

**Comment by volkertb** [comment]
Really? Wasn't that the point of the passthrough functionality that KVM offered, as long as the host system has an IOMMU? The IOMMU would do all the heavy lifting w.r.t. port and address mapping, right?

**Comment by jschwartzenberg** [comment]
I know QEMU has a flag for special handling of VGA cards with IOMMU.

**Comment by stsp** [comment]
No, IOMMU does nothing with ports.
All it does is DMA remapping (well,
also irq remapping sometimes).
But the reality is not as it is written
in the manuals. For example, Intel
IGPs completely ignore IOMMU!
They also have rmrr regions not
marked as such, etc etc. This is
why they gave up fixing their crap,
and just invented GVT to leverage
pass-through.
Other cards are better, but even
many Radeon cards do require
PCI quirks for running bios post,
which is a mandatory operation
for a secondary card pass-through.
dosemu just is not for that kind
of things. qemu is.

**Comment by jschwartzenberg** [comment]
Another issue to mind is that modern GPUs are not known to always have the best VGA implementations.

**Comment by stsp** [comment]
Also KVM itself is buggy as hell, and
the last time I tried to pass-through even
the primary card, I got MCE and reboot,
#634.
We have many KVM breakages.
Intel's KVM maintainer recently said
he will commit some time on fixing
our problems (in KVM itself, not in
dosemu2), but I haven't heard from
him since.

**Comment by jschwartzenberg** [comment]
Maybe you can reach out to him and ask again? It might be good to be able to reach him from here too.
