### ISSUE TITLE
Travis CI?

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1335]
We may need to think again about where and on what to run tests / builds. This morning I received an email about my having a single chunk of 10000 credits, which equates to about 1000 minutes, to run builds/tests across all projects I contribute to. This will run out for me in next to no time. After each user's chunk is exhausted they have to migrate to a minimum $69 per month plan, or lose the ability to build/test their contribution. Here's what the press are saying https://www.theregister.com/2020/11/02/travis_ci_pricng/

Options I know of:
- Github actions
- Gitlab self hosted
- Gitlab hosted
- Jenkins

Ideally I'd not like to be in this situation again, so a less proprietary solution seems better.

Any other ideas?

@tkchia I know you have some experience with Gitlab, can you enlighten us please?

Thanks!

**Comment by stsp** [comment]
Yes, I completely agree we should move
away from paid plans, as no one is making
money from dosemu2 [1]. And besides,
70$/month just sounds like too much anyway.

[1] - This was not always the case, as dosemu2
started as a sponsored project in around 2012.
But the guys who sponsored it, only needed
the specific features (new serial ports emulation
and a fast gfx stack with smooth scaling), and
paid only for that. So I haven't heard from them
since 2014 when this all was (more or less)
implemented.

**Comment by andrewbird** [comment]
Oh, I forgot about Jenkins (I'll add it above). I used to self host that here, but figured that wasn't scalable for general use.

**Comment by tkchia** [comment]
Hello @andrewbird,

> @tkchia I know you have some experience with Gitlab, can you enlighten us please?

Well, GitLab CI is not half bad --- it allowed me to run a longish (almost 2-hour) pipeline for building the `gcc-ia16` toolchain, which was simply not possible on the `.org` Travis CI.

Well, interestingly, I read that GitLab [might also be limiting the CI/CD minutes soon as well](https://about.gitlab.com/releases/2020/09/01/ci-minutes-update-free-users/).  In particular, the free CI/CD minutes might soon be reduced to 400 minutes per month:

> | | Free | Bronze | Silver | Gold |
> | --- | --- | --- | --- | --- |
> | Price | $0 | $4 | $19 | $99 |
> | CI/CD Minutes | 400 | 2,000 | 10,000 | 50,000 |

And, apparently the change was slated to be implemented in October 2020, but [there is (was?) a "glitch"](https://about.gitlab.com/pricing/faq-consumption-cicd/) that caused minutes not to be counted for public projects.  Anyway, they say

> after we resolve an [existing defect](https://gitlab.com/gitlab-org/gitlab/-/issues/243722) for displaying CI/CD minutes for public projects, users will be provided 8 weeks notice (via [our blog](https://about.gitlab.com/blog/) and [this issue](https://gitlab.com/gitlab-org/gitlab/-/issues/243722)) before implementing the CI/CD minute limits.

That aside, my experience with the GitLab CI's free offering was ... quite OK:
  * It allowed me to run a longish (almost 2-hour) pipeline for building the `gcc-ia16` toolchain.   (This was not possible on the `.org` Travis CI.)
  * On the flip side, GitLab CI's container insists on running my code as the `root` user.  This is especially a problem for `dosemu`, since it does not like being run as `root`.

Thank you!

**Comment by andrewbird** [comment]
Even the GitLab Bronze plan at $4 per month would get eaten up quickly by our full test at ~40 minutes. 

One option I've been considering is to run the GitLab Community Edition or Jenkins myself on a hosted Virtual Private Server. So far the downsides I can see are:
 - the VPS provider I use doesn't support hardware assisted KVM on the guest, so our tests would all have to be done in CPU emulation.
 - triggering the build/test from the master Github repo might be a challenge. 
 - I'd be responsible for backup, availability, security and software maintenance.

Hosting either of those test environments on a physical machine is beyond my desire at the moment, so it would have to be a VPS.

Interesting about the running as root thing, a local instance of GitLab could have an unprivileged user we could `sudo` to.

Thanks!

**Comment by tkchia** [comment]
Hello @andrewbird,

> Even the GitLab Bronze plan at $4 per month would get eaten up quickly by our full test at ~40 minutes.
> 
> One option I've been considering is to run the GitLab Community Edition or Jenkins myself on a hosted Virtual Private Server.

In case it might be useful: the GitLab site also mentions a ["GitLab for Open Source"](https://about.gitlab.com/solutions/open-source/join/) scheme.  I do not really have any experience with it though.

Thank you!

**Comment by andrewbird** [comment]
I hadn't seen that, but it does look like a scary process though. I'm speaking to Travis people at the moment about a similar thing for Dosemu2 as it's the easiest option. Should that fall apart I'll move on to this suggestion.

Thanks!

**Comment by andrewbird** [comment]
https://github.com/dosemu2/dosemu2/pull/1353#issuecomment-737261364. Yes, all Dosemu2 credits are gone, you may still have some personal ones though.

I reached out to Travis support again, as I haven't had a reply in 12 days now, but I think we should investigate Gitlab OSS or Github Actions.

**Comment by andrewbird** [comment]
We are still awaiting approval for the OS's account, but in the meantime Travis have raised our limit to 50000 credits, so testing should be working again on the dosemu2 account.

**Comment by stsp** [comment]
What did they say?
Or have you niticed this yourself?

**Comment by andrewbird** [comment]
They emailed much as I just repeated here.

**Comment by stsp** [comment]
Not all setfattr tests seems disabled:
https://travis-ci.com/github/dosemu2/dosemu2/builds/206104198

**Comment by andrewbird** [comment]
Interesting that's the cron job doing the tests across all four DOS flavours. It seems to be picking up incompatibilities in FreeDOS and DR-DOS share implementations on FAT. I can add them as known failures on my next PR, it won't trigger again before the next cron run in one week.
