### ISSUE TITLE
Allow specifying more SDL font details

### ISSUE THREAD

**Issue by stefand** [dosemu2/dosemu2#1427]
Source Code Pro is a relatively thin font. DOS rendering with it looks weird, especially at lower font sizes. It has a bold version, but I haven't found out how to specify details beyond the font family in $_SDL_fonts.

I looked up FcNameParse, but couldn't make examples I found online work. Can you provide some examples how to configure font properties like Bold characters or the font size?

**Comment by stsp** [comment]
I never tried that myself and this code
is written by Andrew, so maybe he will
comment too.
I think you can see the font name via
`fc-list` and provide that to $_SDL_fonts.
There will probably be the gotcha because
we have this:
`strcasecmp(name, foundname)`
where we actually comparing the name
with family name. I think this is a bug
and you'll need to replace that with
strncasecmp() to only compare the
beginning of the name with the family.

**Comment by stefand** [comment]
The multi font approach also potentially causes trouble:

/usr/share/fonts/source-pro/SourceCodePro-Black.otf: Source Code Pro,Source Code Pro Black:style=Black,Regular

Not sure if that is a listing of available fonts, or if "Source Code Pro,Source Code Pro Black" is the right way to specify the "black" thing. If the latter the comma is in the way. Anyway, some other day.

**Comment by stsp** [comment]
But we do not support otf, and I don't
think there is the same problem with ttf.
Or is it?

**Comment by andrewbird** [comment]
Wow, almost two years since I started playing with ttf!

So I see some problems already around sdl_font_idx:
1/ Erroneously used it in call to ` TTF_OpenFontRW()`
2/ Now that the code potentially opens multiple fonts having one font index makes no sense.
3/ We don't use it anyway except for debug message, so I think it should be removed

I loosened up the returned font match checking, seems to be able to select each of the fonts in the Source Code Pro ttf zip file.

**Comment by stefand** [comment]
I tested your sdlttf-02 branch and Source Code Pro Black works OK now. And with $_SDL_fonts = "Source Code Pro:style=Bold" I could select the bold variant.

And now that it is working I don't like the way it looks. It still doesn't have the right proporions and I see why Flexi IBM VGA9 is the default. Unfortunately Flexi IBM VGA9 looks a bit like a non-proportional version of comic sans. 

![qbasic-bold](https://user-images.githubusercontent.com/521262/111827392-233f2e00-88ea-11eb-90b8-a52f3d6c85ae.png)

**Comment by andrewbird** [comment]
You might also try overriding the default with just 'Flexi IBM VGA9 True', or False. One is aspect corrected, one not. So you can have a font that looks like it was on an old non square pixel machine.

**Comment by stuaxo** [comment]
It would be interesting if this could support variants on the same font with different aspect ratios, so if you made the window taller you'd get the True version.

Probably too painful to implement though.

**Comment by stsp** [comment]
> Probably too painful to implement though.

Huh, that's already implemented.
Just try resizing with mouse to the needed
aspect ratio.

**Comment by stefand** [comment]
> Huh, that's already implemented.
> Just try resizing with mouse to the needed
> aspect ratio.
Ah so that's what the double fonts are for.

Could this be where issue 1426 comes from?

**Comment by stsp** [comment]
Very unlikely because for ttf, calling
`SDL_change_mode(0, 0, event.window.data1, event.window.data2); instead`
is the same thing.
It does some plays around renderer
but for ttf it just calls
`setup_ttf_winsize(w_x_res, w_y_res);`
so its the same.

**Comment by stefand** [comment]
1426, not 1428; With my workaround for 1428 I see qbasic jumping from good to bad and back (regarding 1426) with the source code pro font when I change the aspect ratio of the window.

**Comment by stsp** [comment]
It would help if you write #1426 as `#1426`
please.

**Comment by stsp** [comment]
Specify only 1 font and see if that helps.

**Comment by stsp** [comment]
Which I think you already did.
So likely not the case.

**Comment by stsp** [comment]
So everything is fixed.
