### ISSUE TITLE
how to mount drive or remap drive letters?

### ISSUE THREAD

**Issue by gotbletu** [dosemu2/dosemu2#1539]
not sure if this is the default behavior but drive C is not mapped to C. 

how do i remap it so the C: drive is actually the C drive? sorry i try looking at the conf  `cp /etc/dosemu/dosemu.conf ~/.dosemu/.dosemurc` but the explanation are not very clear

```
C:\>lredir
Current Drive Redirections:
C: = /usr/share/dosemu2-extras/fdboot attrib = READ ONLY
D: = /usr/share/dosemu/dosemu2-cmds-0.3 attrib = READ ONLY
E: = /home/heoyea/.dosemu/drive_c attrib = READ/WRITE
F: = /usr/share/dosemu2-extras/freedos attrib = READ ONLY
```

#### try 1
i tryed to delete drive_c
`lredir -d c:`
but it doesn't save changes if i exit and start again, so i skip this

##### try 2
vim ~/.dosemu/.dosemurc
`$_hdimage = "+0 -2 +1"`

```
C:\>lredir
Current Drive Redirections:
E: = /home/heoyea/.dosemu/drive_c attrib = READ/WRITE
F: = /usr/share/dosemu/dosemu2-cmds-0.3 attrib = READ ONLY
```
i thought it would remap E: to C: but thats not the case

##### try 3
`$_hdimage = "+0 /home/heoyea drives/* -3 +1"`
`$_hdimage = "+0 /home/heoyea/.dosemu/drive_c -2 +1"`
errors on bootup or no bootup

----

else if is not possible to remap, is there a way i can start on `E: drive` in this case
`$ dosemu -t` --> goes to `E: drive` on startup

```
Name            : dosemu2-git
Version         : 2.0pre8.r3111.ge3bfe146d-1
OS: ArcoLinux
Kernel: 5.13.13-zen1-1-zen
```

**Comment by stsp** [comment]
Are you installing from git,
or is it somehow pre-packaged?
We do not support 3rd-party
packaging.

**Comment by gotbletu** [comment]
well, dont think theres any official dosemu2 package on archlinux.
only dosemu the original 1 is in the official repository.

was using this https://aur.archlinux.org/packages/dosemu2-git/

but thats fine, thanks for letting me know, guess ill go back to using the original 1

**Comment by andrewbird** [comment]
Rather the switch back why don't you raise an issue with the authors of that package?

**Comment by gotbletu** [comment]
Well is gonna be consider 3rd-party packaging anyways.
I want to respect your rules, i don't want to waste your time if is not supported on my distribution.

**Comment by stsp** [comment]
Yes, we are all for raising such
problems to your distribution.
There is no such rule that we
don't support something by
will. Rather that sometimes
we can't, because _some_
distributions insist on some
particular unsupported layout.
We can't "influence" them, but
YOU can, and of course once
they package the layout that
we support, we will support
you.

@magiblot can you help with
raising that problem to arch linux?

As for what you can do now.
Yes, you can switch to dosemu1,
but most likely you will have to
compile it from sources.
So perhaps there is no any advantage
in doing that, but instead to
compile dosemu2 from sources.
That will work, or at least will put
you to the "supported" camp.

**Comment by andrewbird** [comment]
The point being that the 3rd party package introduces some configuration change that we don't know about that changes how drive c is handled. We produce our own packages for Ubuntu and so can support them, but should Dosemu2 ever be added to the main Ubuntu distro, we could not support their packages either. You mention switching back to Dosemu1 because it's included in Arch and presumably it may well just run out of the box, but if it doesn't then I suppose you'll be speaking to the people over at Arch for the very same reason.

**Comment by stsp** [comment]
> but should Dosemu2 ever be added to the main Ubuntu distro, we could not support their packages either.

But of course we will at least
try, if they do not introduce the
unsupported changes by themselves
(which seems to be the case with
arch, according to what I see in our
bug tracker)

**Comment by gotbletu** [comment]
thats true i might be in the same situation using dosemu1 or dosemu2 =) 
but i dont feel bad about asking for help since is not against their rules for packages they officially build.

honestly, i just wanted to learn how to mount/switch drive letters.
didnt think that was gonna be a problem here regardless of which build/distro i was using.

it was more of a config question then the actual build package, since most people might want to change the default configs anyways.

> The point being that the 3rd party package introduces some configuration change that we don't know about that changes how drive c is handled. We produce our own packages for Ubuntu and so can support them, but should Dosemu2 ever be added to the main Ubuntu distro, we could not support their packages either. You mention switching back to Dosemu1 because it's included in Arch and presumably it may well just run out of the box, but if it doesn't then I suppose you'll be speaking to the people over at Arch for the very same reason.

**Comment by stsp** [comment]
> honestly, i just wanted to learn how to mount/switch drive letters.

There are a few points here.
- The layout they introduce, is
not a default one. As such, if
you rebuild from sources (for
example), there will be no need
to "learn how to switch drive letters".
- The problem is not about renaming
drives: its a much deeper one. Namely
that they decided against distributing
fdpp, which is an important dependency
of dosemu2.

This all means, even if we tell you how
to remap drives, you won't get a fully
functional dosemu2, at least from our
point of view (arch maintainer disagree).
This means you will likely come back
with more subtle problems that we also
can't address, and eventually will give
up on dosemu2 all together.

However, if this is really what you want,
then of course you CAN remap drives.
For example, first you may want to
move your current C drive elasewhere.
Do this:
```
emudrv -n c:
emudrv -d c:
emudrv c: e:
```

First command clones C: to
another letter, and the second
one removes the original C:.
Third one clones E: to C:.
Or you can do instead:
`emudrv -f c: e:`

This will overwrite C: with E:
and won't create any back-up of
old C:.

But again, I have no idea if this
is even going to work on your
build. Believe me, your build is
VERY far from what we have.

**Comment by stsp** [comment]
> it was more of a config question then the actual build package

Its not: their build has entirely
different config rules.
`$_hdimage = "+0 -2 +1"` that
you tried, would work entirely
differently if you build from sources
yourself.
So believe me, we do not (want)
to support you not because we
are bad asses. But dosemu2 in
arch and dosemu2 in our builds,
are basically 2 different emulators.

**Comment by andrewbird** [comment]
> that's true i might be in the same situation using dosemu1 or dosemu2 =)
but i dont feel bad about asking for help since is not against their rules for packages they officially build.

Sure, and that's absolutely the right time to do.

> it was more of a config question then the actual build package, since most people might want to change the default configs anyways.

Yes but from what you showed earlier, that particular drive layout would never occur with either our packages, or the build from our git source, hence our lack of understanding about what's going on. In my opinion there's more than just packaging being done here but changes have been made that affect how Dosemu2 behaves.

**Comment by stsp** [comment]
> our git source, hence our lack of understanding about what's going on.

Well, of course we do understand,
we just pretend that we don't. :)
For us, its quite simple: they dropped
fdpp. For users it should sound like
"we don't understand what have they
done".

**Comment by magiblot** [comment]
My `~/.dosemurc` contains `$_hdimage = "+0 +1 drives/*"` and `lredir` shows the following:

```
Current Drive Redirections:
C: = /home/magiblot/.dosemu/drive_c attrib = READ/WRITE
D: = /usr/share/dosemu/dosemu2-cmds-0.3 attrib = READ ONLY
E: = /usr/share/comcom32  attrib = READ ONLY
F: = /home/magiblot/.dosemu/drives/00-freedos2 attrib = READ/WRITE
G: = /home/magiblot/.dosemu/drives/10-tvision attrib = READ/WRITE
H: = /home/magiblot/.dosemu/drives/11-spider attrib = READ/WRITE
```

But there is one detail regarding the build: the `PKGBUILD` file has the following setting near line 28:

```sh
_opt_fdpp=0
# 0 = use freedos
# 1 = use fdpp and comcom32 (boot only, freedos is still used for utilities)
```

I set it to 1 so that fdpp is used. This requires installing the following packages too:

* https://aur.archlinux.org/packages/fdpp/
* https://aur.archlinux.org/packages/comcom32/

The `PKGBUILD` in each of these contains a line which you should uncomment:

```sh
#pkgname+='-git'
```

Unfortunately, building `comcom32` requires djgpp, which takes very long to build.

**Comment by stsp** [comment]
Thanks for info.

> Unfortunately, building comcom32 requires djgpp, which takes very long to build.

Have they considered fdpp-enabled
build with freecom instead of comcom32?
This will not bring such a major
incompatibilities.

**Comment by stsp** [comment]
Oh, and also I think fdpp enabled
build would be broken because of
that strip bug there?

**Comment by magiblot** [comment]
> For us, its quite simple: they dropped
> fdpp. For users it should sound like
> "we don't understand what have they
> done".

My guess is that the package is outdated. In the comment section of the package you can find the following:

![Screenshot_20210909_233143](https://user-images.githubusercontent.com/20713561/132765397-e99e5c88-74eb-438d-8ed4-16c5adb98e33.png)

So it turns out fdpp support was enabled by default but later disabled, and it hasn't been enabled since then.

> Have they considered fdpp-enabled
> build with freecom instead of comcom32?
> This will not bring such a major
> incompatibilities.

comcom32 is listed as a dependency of the fdpp package. Does fdpp actually depend on comcom32? If not, it should be possible to remove the dependency from fdpp's `PKGBUILD` and build everything without comcom32.

> Oh, and also I think fdpp enabled
> build would be broken because of
> that strip bug there?

Yes, that's another one. For this, @gotbletu, you need to add the following to fdpp's `PKGBUILD`:

```
options+=(!strip)
```

**Comment by stsp** [comment]
> Does fdpp actually depend on comcom32?

No.
Our policy is to depend dosemu2
on fdpp and comcom32. fdpp have
only various libs deps.
comcom32 is entirely swappable.

> options+=(!strip)

Thanks for the help.
Unfortunately such things have a
tendency of making dosemu2 a
bad rep among users. :(

**Comment by stsp** [comment]
I added the work around for that problem.
This will however only hide the fact that
arch provides the non-canonical setup,
rather than to "cure" it properly.

**Comment by gotbletu** [comment]
that change seems to break the `-E` flag
`dosemu -t -E 'c:\program\mpxp165d\mpxplay.exe'`
`dosemu -t -E 'e:\program\mpxp165d\mpxplay.exe'`

it used to semi work on the old build, but now it just crashes

**Comment by stsp** [comment]
Right, COMSPEC had to be updated.
Should now be better.

**Comment by gotbletu** [comment]
thanks for the update, that works ok now

P.S `-K` flag has never worked for me even on the old build, is that a known issue?

`dosemu -t -K '/home/heoyea/.dosemu/drive_c/program/mpxp165d/mpxplay.exe'`
or
`dosemu -t -K ./mpxplay.exe`


it would always crash, so i had to use `-E` instead of `-K`

**Comment by gotbletu** [comment]
my configs are back to default

this works fine
`dosemu -t -T -E 'c:\apps\vim\EDIT\VIM\VIM.EXE'`

this always errors
`dosemu -t -T -K ./VIM.EXE`
```
ERROR: libao: unable to open output device
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
Expression 'alsa_snd_pcm_hw_params_set_buffer_size_near( pcm, hwParams, &alsaBufferFrames )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
Expression 'alsa_snd_pcm_hw_params_set_buffer_size_near( pcm, hwParams, &alsaBufferFrames )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib Invalid field
ALSA lib Invalid card '
ALSA lib Invalid field
ALSA lib Invalid card '
ALSA lib unable to open slave
Cannot connect to server socket err = No such file or directoryCannot connect to server request channeljack server is not running or cannot be startedJackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlockJackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlockERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:235:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: INT21: redirecting /home/heoyea/.dosemu/drive_c/apps/vim/EDIT/VIM failed (err = 15)
```

**Comment by andrewbird** [comment]
> ERROR: INT21: redirecting /home/heoyea/.dosemu/drive_c/apps/vim/EDIT/VIM failed (err = 15)

It's an old FreeDOS kernel (1.2 or less), the soon to be released 1.3 will fix it.

**Comment by stsp** [comment]
Thank you.
So on arch, everything is broken.
But we used to detect the old kernel
and print an error that we do not
support this freedos version. Do you have an
idea when this went away and stopped
erroring?

**Comment by stsp** [comment]
A note for others: the fix that Andrew
mentions (NOT thank you for the fix,
but thanks for mentioning it :) is only
needed on arch.
Nothing is broken in our packaging.

**Comment by andrewbird** [comment]
> But we used to detect the old kernel
and print an error that we do not
support this freedos version.

I don't remember that, so I just tried re-enabling a test that I know will break on FreeDOS 1.2. Nothing appears on linux console, but DOS window shows
~~~
C:\>lredir X: /tmp^M                                                            
Error f (invalid drive) while redirecting drive X: to \\LINUX\FS/tmp^M          
lredir is not supported with this freedos version^M                             
~~~
That 'lredir is not supported with this freedos version' message appears to be part of lredir itself, so if the drive is being mapped internally by the use of the `-K` option I doubt it'll appear anywhere.

**Comment by andrewbird** [comment]
Also a note for @gotbletu , this failure to map the drive wouldn't have appeared under Dosemu1 or perhaps two years ago under Dosemu2. Our drive mapping now relies upon a function in the DOS kernel that is currently broken in the released version of FreeDOS, but works in all other DOS versions. The fix has been applied upstream and we are just waiting for a release to make it generally available. If you want to try it out, you can grab a pre-release kernel from https://github.com/FDOS/kernel/suites/3559249629/artifacts/85396420. Either of the K*.sys files can be renamed to kernel.sys and used to replace the defective on on your installation.

**Comment by stsp** [comment]
I added the check for -K.
@gotbletu could you please check
that the error msg have improved?

**Comment by gotbletu** [comment]
yea it has a better error message now

```
$ dosemu -t -T -K ./VIM.EXE

ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
Expression 'alsa_snd_pcm_hw_params_set_buffer_size_near( pcm, hwParams, &alsaBufferFrames )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
Expression 'alsa_snd_pcm_hw_params_set_buffer_size_near( pcm, hwParams, &alsaBufferFrames )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib Invalid field
ALSA lib Invalid card '
ALSA lib Invalid field
ALSA lib Invalid card '
ALSA lib unable to open slave
Cannot connect to server socket err = No such file or directoryCannot connect to server request channeljack server is not running or cannot be startedJackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlockJackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlockERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:235:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: INT21: redirecting /home/heoyea/.dosemu/drive_c/apps/vim/EDIT/VIM failed (err = 15)
ERROR: -d/-K is not supported with this freedos version
```

**Comment by stsp** [comment]
I don't know if you are already aware,
but, according to your messages, alsa
is misconfigured too. So you will not
get any audio.

**Comment by gotbletu** [comment]
i have to use sdl since the default auto detect doesnt do anything
`$_sound_driver = "sdl"`
but sound works with sdl no probs

> I don't know if you are already aware,
> but, according to your messages, alsa
> is misconfigured too. So you will not
> get any audio.

**Comment by stsp** [comment]
So does anyone have an idea
what is the state of dosemu2
in arch now, 2 years passed?
Have they managed to fix that
strip problem, or at least update
the freedos for -K to work?
