### ISSUE TITLE
Alcatraz triggers all sorts of odd behaviors and is generally slow

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1669]
**Describe the bug**
The first time I ran the game it was slow. Then it crashed DOSEMU2, now it showed messages like:
```
ERROR: vtmr 0 already requested
ERROR: MCB corruption, good:00b5:0000 bad:146e:0000

ERROR: fdpp: abort at memmgr.cc:456
```

**To Reproduce**
Steps to reproduce the behaviour:
Install the game.
Run the game.

**Attach program/game binaries or provide an URL**
[alcatraz.tar.gz](https://github.com/dosemu2/dosemu2/files/8885732/alcatraz.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8885733/boot.log)

**A regression?**
Unknown

**Comment by stsp** [comment]
> ERROR: vtmr 0 already requested

I think this is already fixed.

> A regression?
> Unknown

Would be good to try a week-old
build, before threading.

**Comment by jschwartzenberg** [comment]
Yeah this one is affected a lot by the recent changes. It runs very fast in b10018cc6393d083f385c3ac0ae3d7ba20115c7e

**Comment by stsp** [comment]
But it is likely already fixed.

**Comment by jschwartzenberg** [comment]
It crashes now with the latest revision.
[boot.log](https://github.com/dosemu2/dosemu2/files/8885876/boot.log)

**Comment by stsp** [comment]
So only `ERROR: vtmr 0 already requested`
is fixed, right?

**Comment by jschwartzenberg** [comment]
Yep, that one is fixed.

**Comment by stsp** [comment]
> Yep, that one is fixed.

Please check if the remaining
one is fdpp-specific (by running
on non-fdpp).

**Comment by jschwartzenberg** [comment]
FreeDOS 1.2 gives me a glitched intro and at some point:
![Screenshot_20220612_161613](https://user-images.githubusercontent.com/877112/173237573-8d5d7a37-367d-434a-9dc7-a5980aca1e9f.png)

Oops, I forgot the `boot.log` is in a different spot with `-dos`, there the correct one: 
[boot.log](https://github.com/dosemu2/dosemu2/files/8886020/boot.log)

**Comment by stsp** [comment]
Wow, so same MCB corruption
as in an fdpp?
Interesting, but please try MS/PC
dos.

**Comment by jschwartzenberg** [comment]
With MS-DOS 6.22 DOSEMU2 crashes: 
[boot.log](https://github.com/dosemu2/dosemu2/files/8886019/boot.log)

**Comment by jschwartzenberg** [comment]
I corrected the FreeDOS log, I accidentally put the FDPP log there.

**Comment by stsp** [comment]
`$_timer_tweaks = (on)` and you
are good.

**Comment by stsp** [comment]
Please update wiki and lets close. :)

**Comment by jschwartzenberg** [comment]
Done! Updating this TOC separately sucks. Can't it at least be generated?

**Comment by stsp** [comment]
No idea, maybe @rouyng can
help you.

**Comment by rouyng** [comment]
Yeah, making the TOC manually is annoying. Oddly enough, Github wiki _does_ automatically generate a TOC for each wiki page, but it puts it in the sidebar where it is pushed to the bottom by the other wiki page links. It's cumbersome and difficult to read. 

If we want a TOC at the top of the document like we have now, we either need to manually generate it or use an external tool. [github-markdown-toc](https://github.com/ekalinin/github-markdown-toc) is a simple tool to generate the TOC. You could even set it up using github actions, but I'm not sure if the added complexity there is worth it. Instead, I've added a (non-rendered) comment to the Tweaks wiki page linking to the github-markdown-toc tool. So hopefully anyone editing it will be able to save some time by using that.

What would be really nice is if GitHub supported `[[_TOC_]]` like GitLab does. This lets you insert the auto-generated TOC wherever you want in the document. For now, we can hope!

**Comment by jschwartzenberg** [comment]
What about switching to markdown in a Git repo instead of editing wiki pages by hand?

**Comment by stsp** [comment]
What will this give us?
I am pretty sure more ppl
are willing to work on our
docs on-line. Wiki proved
its viability world-wide, as
well as in our project.
I don't want to return to
updating the docs manually,
asking people to create a PR
(which they will refuse to do
99% of the time), etc.

**Comment by jschwartzenberg** [comment]
I think this might also have been the result of people not being fully familiar with the docs format and html generation process.

**Comment by stsp** [comment]
I don't think so because
modifying off-line docs and
creating a PR requires 10 times
more efforts. Note that most
people here (even the very
active bug reporters) never
dealt with git, to start with.
They use our PPA/copr.

I just strongly vote for wiki
because that removes most
of the responsibility from me
at maintaining docs... which
I didn't do anyway, but with
wiki there is a hope that others
would. I only kept man pages
up to date, and with other docs
in wiki, that would be enough.

Even if there is someone who
wants to maintain the docs and
wants them being off-line (like
you), should do it in the separate
repo. I am fine with that, so if
you want to maintain the off-line
docs, please create the repo
and we'll have a separate -docs
package. This is quite a common
practice too. But if you don't want
to maintain the off-line docs, then
they will cease existing just as a
matter of fact. Wishing them to
stay w/o acting at maintaining
them, is just not productive.

**Comment by stsp** [comment]
So don't treat it as a decision
that I can either make or not make.
No, this is a search of a model
that would make our docs viable.
I don't know what such a model
should be, but I do know that the
docs should first be excluded from
the main repo, because them being
there proved the non-viability for 10
years.
Where they end up, can be discussed,
but wiki is the most obvious
destination.

**Comment by andrewbird** [comment]
I think GitHub wikis are stored under git and can be used as a submodule from the main repo for your offline use.

**Comment by stsp** [comment]
https://github.com/dosemu2/dosemu2.wiki.git
Thanks for that info!
So its already in a separate repo.
Just the way it should be. :)

**Comment by rouyng** [comment]
I noticed that before, but I couldn't push changes to the origin repo (which makes sense since I don't have any special role). Since it's a separate repo than the main project one, I'm not sure how contributors could open pull requests. Without PRs, it seems you would have to actually make changes through the wiki interface? I think it makes sense to keep the wiki for documentation, but there are some annoying design decisions by GH that make wikis a sort of second class citizen.

**Comment by stsp** [comment]
Move to gitlab?

**Comment by andrewbird** [comment]
Ci minutes are metered even for free projects, I think.

**Comment by stsp** [comment]
Same as here. :)

**Comment by andrewbird** [comment]
Not quite, Gitlab 400 minutes per month, Github 2000.
