### ISSUE TITLE
Police Quest 4, mouse move causes crash

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1727]
**Describe the bug**
The game loads but moving the mouse causes a crash.

**To Reproduce**
Run the game (`sierra`) and move the mouse.

**Attach program/game binaries or provide an URL**
[pq4.tar.gz](https://github.com/dosemu2/dosemu2/files/9078703/pq4.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/9078704/boot.log)

**A regression?**
unknown

**Comment by stsp** [comment]
Not only mouse.
Quickly pressing/releasing
multiple buttons also hangs
eventually.

**Comment by stsp** [comment]
That was quite a challenge...
The only remaining problem is
the hang if you click on a QUIT
button.
Here is the fix:
```
Comparing C:\d\games\pq4\sbpro.old and C:\d\games\pq4\sbpro.drv
00000B3F:     E2  90
00000B40:     FD  90
```

So please update the doc
and lets close.

**Comment by stsp** [comment]
One of the problems was that
this prog forgets to clear ss/sp
on DPMI funcs 0x30[012].
For the first time ss/sp is cleared,
but on return the real stack addr
is put there, which corresponds
to internal DPMI area. Since this
prog uses static buffer for regs
struct, the same stack addr remains
on subsequent 0x30X calls, but
it may be occupied at that point.

I've found that this bug is quite
common. Even djgpp's stub forgets
to clear ss/sp on subsequent calls.

@Baron-von-Riedesel do you
happen to use the work-around
for that?

**Comment by Baron-von-Riedesel** [comment]
> do you happen to use the work-around for that?

I remember that I once checked if rmcs.rSSSP in int 31h, 300|1|2h should be updated by the host, and quickly found out that it must not be changed.

**Comment by stsp** [comment]
What do you mean, you've found
other dpmi impls not?

**Comment by Baron-von-Riedesel** [comment]
>  ... you've found other dpmi impls not?

Yes. I can't remember what I did check then, but I just checked the Win98SE host: it does NOT modify SS:SP in rmcs.

Btw, another thing perhaps worth to discuss in DosEmu's DPMI implementation: int 31h, ax=0009 ( set access rights ) - it's very questionable that DosEmu does NOT ignore the "granularity" bit in register CX. IIRC, other hosts do so, the descriptor limit is exclusively set by int 31h, ax=0008h.

**Comment by stsp** [comment]
> Yes. I can't remember what I did check then, but I just checked the Win98SE host: it does NOT modify SS:SP in rmcs.

OK, thanks for info.

> Btw, another thing perhaps worth to discuss in DosEmu's DPMI implementation

But I'd rather not touch what
seems to not cause any problems.
If this is needed to run WD then
of course its discussable.

**Comment by Baron-von-Riedesel** [comment]
> If this is needed to run WD then of course its discussable.

No, that's not related to WD.
WD is a difficult thing. The problem is that it expects to run exclusively as a client, with noone modifying its interrupt vectors. 
The best and simplest thing to do would be to just start another DosEmu session and let them communicate thru some virtual Int 14h device. A trap file SER.TRP already exists for remote debugging...

**Comment by stsp** [comment]
> The problem is that it expects to run exclusively as a client, with noone modifying its interrupt vectors.

You mean, the DPMI-1.0 way,
i.e. per-client IDT? Or what is
the problem?

**Comment by Baron-von-Riedesel** [comment]
> You mean, the DPMI-1.0 way, i.e. per-client IDT? 

Exactly. WD did run with HDPMI was instructed to separate clients ( own IDT and LDT, own address context ).

To make things even more compatible I recently added an API in HDPMI to "disable" the host and this API is now called in my modified version of WD ("disable" means that the host will "hide" itself in Int 2Fh, ax=1687h ) - this ensures that the DOS-extended debuggee will install its very own host and HDPMI isn't involved at all.

**Comment by jschwartzenberg** [comment]
> So please update the doc
> and lets close.

Will add this to the wiki. Quest for Glory 4 seems to have the same issue and contains the same file:
```
[julius@elleboog drive_c]$ md5sum  qg4/sbpro.drv  pq4/sbpro.drv
162d35e8828f43fe2fcd087aadddf851  qg4/sbpro.drv
162d35e8828f43fe2fcd087aadddf851  pq4/sbpro.drv

**Comment by stsp** [comment]
Own idt and rest is interesting, but what
kind of an api is there to put client into
foreground, ie activate its paging context
and idt?

**Comment by Baron-von-Riedesel** [comment]
> but what kind of an api is there to put client into foreground, ie activate its paging context and idt?

You asked that already a few years ago and most likely didn't understand my answer.

The answer is/was: There's no API necessary. Since the IDTs/LDTs are different, there's no direct way to switch from one client to the other - the only way to "switch" is by the first client entering real-mode, and then enter the second client by a real-mode callback or raw jump. And in that real-mode callback/raw jump must be code to activate the context for the second client.

**Comment by stsp** [comment]
Admittedly I still don't
understand that answer.
If you have 2 unaware
clients (and debugee is
certainly unaware of a
debugger), what kind
of a callback it is going
to do?
Or even if debugger is
aware of debugee, it
still didn't allocate an RM
callback on behalf of a
debugee, so how would
it switch?

Currently dosemu2 has
a notion of client switching.
It does so on return from
real mode, because all
multitaskers switch stack
in real mode.

**Comment by Baron-von-Riedesel** [comment]
> If you have 2 unaware clients (and debugee is certainly unaware of a debugger), what kind...

WD, if debugging protected-mode apps, consists of actually 2 programs: WD itself, and a "trap" binary ( usually combined with a "trap helper" binary ). The trap helper is a protected-mode app that runs in the context of the debuggee. The "trap" binary is a real-mode application. The communication takes place between trap helper binary and WD, and the communication path is actually: WD-> trap -> trap helper -> trap -> WD. The debuggee itself is unaware of that, of course.

So WD is actually just a frontend for the "real" debugger, which is the "trap helper".

**Comment by stsp** [comment]
Ah but for that you usually
need the 0xc0[01] fns which
AFAIK only dosemu2 implements.
But maybe they used some
hack.
Anyway, dosemu2 already has
a notion of client switching
and per-client IDT (but not LDT).
If you can provide a simple test-case,
then adding a switch to rmcb
is a 10-minutes work.

**Comment by stsp** [comment]
```
--- a/src/dosext/dpmi/dpmi.c
+++ b/src/dosext/dpmi/dpmi.c
@@ -3112,6 +3112,7 @@ static void dpmi_realmode_callback(int rmcb_client, int num)
     if (rmcb_client >= in_dpmi || num >= DPMI_MAX_RMCBS)
       return;
 
+    set_client_num(rmcb_client);
     D_printf("DPMI: Real Mode Callback for #%i address of client %i (from %i)\n",
       num, rmcb_client, current_client);
     DPMI_save_rm_regs(DPMIclient[rmcb_client].realModeCallBack[num].rmreg, ~0);
```
Something like this may help.
It switches IDT.

**Comment by Baron-von-Riedesel** [comment]
Switching the IDT would indeed suffice. But some sort of API is additionally needed. A client ( WD ) must somehow tell DosEmu: please give me my very own IDT, I don't want to share it with any client that I'm going to launch.

> But maybe they used some hack.

AFAICS they implemented all those communications with raw mode switches.

**Comment by stsp** [comment]
IDT is already not shared.
And the switching API is there,
it currently works on return from
realmode. Can be added for
rmcbs as shown above. Or for
raw mode switches:
```
@@ -5439,6 +5440,7 @@ done:
     _edx = 0;
     _esi = 0;
     _edi = 0;
+    set_client_num(Segments[_cs >> 3].used - 1);
 
   } else if (lina == DPMI_ADD + HLT_OFF(DPMI_save_restore_rm)) {
     unsigned int buf = SEGOFF2LINEAR(SREG(es), LWORD(edi));
```

We track what segment was
allocated to which client (hence
single LDT!) so everything is
already implemented.

**Comment by Baron-von-Riedesel** [comment]
But it's impossible to switch IDTs generally. Often clients WANT to share the IDT with any program they launch.

See my DPMI.EXE with the -z cmdline option. It checks exactly that case - it intercepts int 0x21 and then launches another instance of itself. The output of that instance ( via int 0x21, ah=2 ) is intercepted and changed to UPPERCASE. This can only work if the IDT is SHARED.

**Comment by stsp** [comment]
IDT doesn't need to be shared.
Populating IDT on start from previous
IDT is quite enough.

**Comment by Baron-von-Riedesel** [comment]
> Populating IDT on start from previous IDT is quite enough.

I guess that I understand now. However, "NOT shared" doesn't just mean that there exist 2 IDTs, but that the second one does NOT inherit the vectors from the first, that is, an IDT  is always in an "initial" state when a client starts, so that none of the first client's code segments is in any interrupt chain of the second client.

**Comment by stsp** [comment]
This is perfectly fine with me.
Inheriting doesn't happen if the
particular DPMI extensions were
probed (because pharlap has
problems with inheriting).
We can add to that list.
