### ISSUE TITLE
Can dosemu send a SysReq keypress condition to DOS?

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1780]
### Discussed in https://github.com/dosemu2/dosemu2/discussions/1761

<div type='discussions-op-text'>

<sup>Originally posted by **ecm-pushbx** August  6, 2022</sup>
I'm working on porting over https://hg.pushbx.org/ecm/fddebug/rev/e996e6ff7fb1#l1.216 to lDebug. However, both on dosemu2 and on a hardware machine I am unable to trigger either [the interrupt 15h service 8501h call](https://fd.lod.bz/rbil/interrup/bios/1585.html#1558) or the interrupt 09h (IRQ #1) call that leaves [the keyboard flags](https://fd.lod.bz/rbil/memory/keyboard/m00400018.html) at `byte [40h:18h]` with bit 2 (mask 4) set.

On dosemu2 one problem is that the window never appears to receive the SysReq key as it is intercepted by the window manager (or something like that) and creates a screenshot. However, disabling this in "Keyboard Shortcuts" still doesn't allow dosemu2 to receive it, or it might be dosemu ignores it.

Both methods also seem to fail on my hardware machine as I mentioned. Suggestions are welcome.</div>

**Comment by stsp** [comment]
Per https://github.com/dosemu2/dosemu2/discussions/1761#discussioncomment-3583847
that sounds convincing, transferring
to issues.

**Comment by stsp** [comment]
Should now be fixed
(patch untested).

**Comment by ecm-pushbx** [comment]
The comments say Alt-SysReq. Should I try this?

**Comment by stsp** [comment]
Well, isn't Alt-PrintScreen == SysRq?

**Comment by ecm-pushbx** [comment]
Then my prior tests are invalid because IIRC I only pressed the key labelled SysReq, not Alt.

**Comment by stsp** [comment]
Maybe you have it as a separate
key. But I believe it would still result
as if Alt was pressed too.

**Comment by ecm-pushbx** [comment]
I did test now with Alt+Print/SysReq. The key is labelled "Druck" (Print) on top and "S-Abf" (S-Req) on the front.

Using an lDebug build with the build options as in `./mak.sh -D_CATCHSYSREQ -D_SYSREQINT=15h` I can get the expected int 15.8501 call, both prior to this commit and after it. However, apparently the int 9 handler is not done with its I/O at this point because the keyboard appears to "lock up" and not accept any more input. I worked around this by running the command `rc.replace g; tp 100` and then `rc`, then interrupting the running debuggee using Alt+SysReq. This suffices to finish dosemu's int 9 handler and regain control in the debugger (keyboard input usable). The test program I used is at https://pushbx.org/ecm/test/20220907/testwait.com (No source, entered into the debugger and saved as an executable.) It loops for about 8 seconds when running.

An lDebug build with `-D_CATCHSYSREQ -D_SYSREQINT=09h` did not work before, but does work with this commit. Unlike the int 15 method this one appears to finish all keyboard I/O in the called original int 9 handler. So that's definitely more comfortable.

I also tried Alt+SysReq on my physical machine now (AwardBIOS), and both methods also work for this. However, unlike dosemu2, it appears that the ROM-BIOS's int 9 handler finishes sending EOI and whatever other I/O it does before it calls down to int 15.8501. So both methods are readily usable on this machine, unlike dosemu2 for now.

**Comment by stsp** [comment]
Well when you call int15 you
still get IF clear in a handler.
So why does it matter if int9
did EOI or not?

**Comment by ecm-pushbx** [comment]
The debugger will upon entry enable interrupts then enter its command line input loop. It expects to receive keyboard input then, unless using serial I/O, or redirected input, or receiving commands from a script file or RE buffer or RC buffer. So it hangs when the int 15 is called before EOI.

**Comment by stsp** [comment]
OK, another untested patch here.

**Comment by ecm-pushbx** [comment]
Thanks, will try it tomorrow probably.

**Comment by ecm-pushbx** [comment]
Works very well, thanks!
