### ISSUE TITLE
64bit address space unsupported by jit

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1839]
While porting to ARM, I've found out
that we still do not support 64bit address
space.
Patch #1838 enables the 64bit address
space, and nothing works.
This needs to be fixed.
For the start, someone needs to find out
how much of the dependencies are there
on 32bit, and where are they.

**Comment by stsp** [comment]
Of course we can do something like
#1018 and stick into hacks forever
instead of writing a proper 64bit support.
Or perhaps I should just drop those
porting efforts (as always) and admit
that dosemu1 code wasn't sufficiently
eliminated yet to seriously consider
any portability.

**Comment by stsp** [comment]
OK I amended things a bit.
With KVM's SYNC_MMU extension it
appears possible to mmap shm into
pre-allocated areas and back, so the
weird ptr wraps are avoided.

But jit is still not 64bit-safe. And in fact
even changing int to long for jit's
mem_base doesn't work because the
struct gets out of 128 bytes.

**Comment by stsp** [comment]
I suppose sim doesn't look at TheCPU.mem_base,
as it started to work together with kvm
rather magically.

**Comment by bartoldeman** [comment]
I tried this as well and it boots for me.

For the JIT it may be best to put the membase in r8 or some other "new" 64-bit register, since it now uses 32-bit arithmetic to calculate addresses (which has the advantage that they wrap at 4G). Then it could just uses addresses such as `(%r8+%rdi)` instead of `(%rdi)` (zero extended from `%edi`. But this is of course a fair amount of work.

**Comment by stsp** [comment]
And on i386?
Won't it be better to extend the
access to TheCPU struct for a
word offsets?

**Comment by stsp** [comment]
Sim has bugs on arm.
It works somewhat, but not quite.
I suspect some problems with flags,
for example in comcom32 memmove()
sometimes doesn't work as expected.

**Comment by stsp** [comment]
I actually am not sure what
problem will %r8 solve. Are we
out of i386 regs already?
Even if we are, there are other
interesting things to consider.
Eg using LDT %gs, which on
x86_64 will be the use of wrgsbase.
But IMHO allowing the word
access to CPU struct is needed
anyway.

**Comment by stsp** [comment]
> For the JIT it may be best to put the membase in r8 or some other "new" 64-bit register, since it now uses 32-bit
> arithmetic to calculate addresses (which has the advantage that they wrap at 4G).

But the whole purpose of that exercise
was to get rid of any wrapping.
I don't think we need any now as there
should be nothing interesting below
mem_base. There was LDT below mem_base,
and I hacked it into the main dpmi pool
now. So I really think %rdi should be enough
as a base.

**Comment by stsp** [comment]
Let me ascii-art a bit for better understanding.
Legacy address space (before yesterday's
patches) looked like this:
```
| high space, nothing interesting should be here
| 4G-aligned wrap address, say 0x200000000
| Low DOS space
| mem_base, unaligned to 4G
| High DOS space, wrapped
| 4G-aligned boundary, 0x100000000
| low space, nothing interesting should be here
```

Now we get to this:
```
| high space, nothing interesting should be here
| 4G-full DOS space, unaligned to 4G
| mem_base, unaligned
| low space, nothing interesting should be here
```

In that model its quite important that DOS space
is no longer split, and is no longer aligned to 4G.
This means that you need to add mem_base as
a last step, after all wrap masking is done. Because
adding mem_base may now cross the 4G boundaries.
So what you suggest, is actually contrary to my
yesterday's patch.

**Comment by stsp** [comment]
Note that this should still be
compatible with the 32bit addressing
(I hope) because uintptr_t (or any
other ptr arithm) should wrap on 32bit
arches just as before.

**Comment by stsp** [comment]
Hmm, and I probably missed the
native dpmi case here.
In that case IIRC we set the bases
to -mem_base to compensate an
offset, which then wraps in compatibility
mode but no longer wraps on host...
I guess the tests passed only because
we are not touching the upper parts of
address space during testing. But I
suspect I need to keep the wraps for
CPUVM_NATIVE.

**Comment by stsp** [comment]
Obviously even sim isn't ready for
64bit address space. ModRMSim()
has this:
`TheCPU.mem_ref = AR1.d - TheCPU.mem_base;`
So it seems mem_base is populated
within intermediate arguments, which
should not happen. Would you like to
take a look at this mem_base stuff?
Maybe sim in unstable on arm because
of that. (but most probably not)

**Comment by stsp** [comment]
Why sim needs the custom handling
on a mem_base, instead of just using
READ_xxx() macros as all polite people
do? :)

**Comment by stsp** [comment]
So it appears mem_base is coded into
segment bases, instead of in the load/store.
Hence the problem, because you need
to wrap the pointer after adding a segment
base. But in load/store you can add mem_base
after wrap.

**Comment by bartoldeman** [comment]
yes, having mem_base coded in the segment bases (an optimization since it avoids one addition in membase+segment_base+offset) is the reason why this isn't a quick change.

There are some ways to do this, putting mem_base in a register is the quickest I think (and even on i386 ebp is unused, but need to be careful using ebp, as the JIT calls C code). Then the general load/store, often like `mov [edi],al` could be `mov [edi+ebp],al`. Using a field in syncpu is possible even with byte offsets (by shifting cr[] a little, as only cr[0] is used in compiled code), just adds another `add` in the address generator.

Note that word offsets in compiled code don't exist, has to be dword, so JIT code would quite a bit larger. On the other hand it doesn't need to be wholesale, e.g. we use dword offsets for stub_read_xx already (generated read instructions add enough nop instructions for patch space).

**Comment by stsp** [comment]
Well, as an intermediate step we can
of course get back to the wrapped space.
What we really need and can't avoid, is
the full 64bit mem_base. And also we can't
mmap() freely any more because the
pointer may not be within the 4G reachibility,
but this is already done.
So will this help a transition if the unwrap
is temporary reverted?

**Comment by bartoldeman** [comment]
sorry, I'm a bit lost here what unwrap you mean exactly. You propose reverting which commit/patch exactly?

**Comment by stsp** [comment]
There is no particular revert.
But in 775596cda you can see
the if0'ed example of keeping
the wrapped address space with
64bit mem_base. You can do
`off = (uint32_t)(baddr + a) | (baddr & ~0xffffffffUL);`
which gives you some compatibility
back.

**Comment by stsp** [comment]
I decided to not do that because
currently it doesn't help: kvm is good
in any case, dnative needs MAP_32BIT
and simx86 doesn't support 64bit mem_base.
This is why the example is disabled, and
later even removed. :)
But it may still help a transition.

**Comment by bartoldeman** [comment]
Don't have time to look at this in detail now, but for sim I did most of the work in March 2020 (b2208b95, #1083)
`cpu-emu.c:      TheCPU.mem_base = CONFIG_CPUSIM ? 0 : (uintptr_t)mem_base;`

I think then
`TheCPU.mem_ref = AR1.d - TheCPU.mem_base;`
could be rewritten as
`TheCPU.mem_ref = AR1.d`.

For Arm (congrats on all the progress!) I think it would be best to run the DJGPP CPU tester and compare output to x86, to see if there's anything obvious. I presume that it's little endian and non-aligned memory accesses allowed? If not it would be more work I think?

**Comment by stsp** [comment]
> could be rewritten as

Done, thanks.
So in this case sim is fine with
64bit mem_base and unwrapped
address space, which is good to
know. The bad thing is then that
the failure reason is unknown.

> For Arm (congrats on all the progress!) I think it would be best to run the DJGPP CPU tester

Easier said than done.
Sim is very unstable, and while
the boot goes to `C:\`, most of it
actually skipped, and running
some prog (like CPU tester) is
currently not possible because
comcom32 crashes if you run
something.

**Comment by stsp** [comment]
And yes, the fact that we get to `C:\`
suggests that there are no problems
with byte-ordering or alignment.
Otherwise it would crash much
earlier.

**Comment by stsp** [comment]
[a.txt.gz](https://github.com/dosemu2/dosemu2/files/10251257/a.txt.gz)
Managed to grab the log.
Note that SIGSEGV happens on FPU tests.

**Comment by stsp** [comment]
OK fixed. :)

**Comment by stsp** [comment]
Andrew could you please adjust
your tests to use assembler and
linker from Makefile.conf, which
means those found by configure?
Otherwise your tests fail to build
on arm.

**Comment by stsp** [comment]
Hmm, all tests failed on CI.
Andrew, what can be wrong here?
It works locally.

**Comment by stsp** [comment]
> could be rewritten as

OK, that was a bad suggestion.
ModRMSim() is called directly from
interp. So we are still quite far from
being 64bit-safe here. :(

**Comment by stsp** [comment]
> For Arm (congrats on all the progress!)

Thanks, although, as you realize, the
arm port w/o jit is just a POC...
Which means tcg, not more not less.
Anyway, that was an interesting task with
` 141 files changed, 3276 insertions(+), 2581 deletions(-)`
outcome.

**Comment by stsp** [comment]
OK, not funny, all tests are still
failing. The number of failed tests
is higher than the number of run
tests. :)
Andrew any idea what's up there?

**Comment by andrewbird** [comment]
Tests that have subtests, each subtest failure is counted.

**Comment by stsp** [comment]
So what fails?
Everything seems to work, no?

**Comment by andrewbird** [comment]
No idea, where is your problem test run?

I just pushed a fix to use the configured host compiler for the CPU test, but will it work on ARM?

There are other tests that use gas to create .com files, probably not a quick fix there. Do you think I could use the ia16 version instead?

**Comment by stsp** [comment]
https://github.com/dosemu2/dosemu2/actions/runs/3719332725/jobs/6308126653
Test run is here, I thought you are
receiving the failure notification emails?
Every test broke, how is so?

**Comment by stsp** [comment]
> I just pushed a fix to use the configured host compiler for the CPU test, but will it work on ARM?

I am not even sure this is needed.

> There are other tests that use gas to create .com files, probably not a quick fix there.

Yes I mean those.

> Do you think I could use the ia16 version instead?

Whatever works.
If there are the arm build of ia16-xx in PPA
then feel free to, otherwise not.

**Comment by andrewbird** [comment]
> Test run is here, I thought you are
receiving the failure notification emails?

No I only see my own.

It seems like for each test, the DOS failed to boot. Since there are so many tests and each one has to timeout, the total test time was around 3 hours. Perhaps this was an older test run that 'suddenly' completed and surprised you in the middle of your current work.
~~~                                                                               
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.9 installed.
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)
Process 0 starting: F:\command.com /e:384 /p /k %FDPP_AUTOEXEC%

DPMI: Unhandled Exception 0e - Terminating Client
It is likely that dosemu is unstable now and should be rebooted
ERROR: DPMI: Warning: trying to leave DPMI when in_dpmi_pm_stack=1
ERROR: DPMI: App is working on host's PM locked stack, expect troubles!

Shell F:\command.com exited, press any key...
~~~



>>    Do you think I could use the ia16 version instead?

>Whatever works.
If there are the arm build of ia16-xx in PPA
then feel free to, otherwise not.

Switching those to tests to use NASM might be better, but your response also highlights that the other tests based on djgpp and ia16 will have problems too. I'm not sure whether the test suite can be made ready to work on ARM in the near future, as most tests have sources compiled for DOS at test time.

**Comment by stsp** [comment]
> Perhaps this was an older test run that 'suddenly' completed and surprised you in the middle of your current work.

Phew, thanks, so that's a good news. :)

> I'm not sure whether the test suite can be made ready to work on ARM in the near future

I am not sure what you mean.
Under arm we install the i386 cross
tool-chain. You only need to get it from
Makefile.conf, so what is the problem?

**Comment by andrewbird** [comment]
> I am not sure what you mean.
Under arm we install the i386 cross
tool-chain. You only need to get it from
Makefile.conf, so what is the problem?

The test suite is creating DOS binaries to be run within the booted DOS session. The only exception to that is the original Dosemu CPU test which also creates a native host binary to create a reference output file to compare the DOS results to.
Some of the tests currently use the host's `as`  and its `gcc` to link .com files, but most others use djgpp and ia16 to create DOS executables. It seems to me that if ARM distro provides NASM that could be used instead of its `as/gcc` ( or perhaps use the cross tool chain) but a lack of djgpp and ia16gcc for ARM is a bigger problem.

**Comment by stsp** [comment]
Its not a bigger problem, its just
a matter of asking its maintainers
to enable the arm build in PPA.
But so far can we convert the rest,
whatever uses gas?

**Comment by andrewbird** [comment]
A quick grep shows that there are only 21 tests that use gas.

So which Makefile.conf variables hold the cross i386 `gcc/as` names?

Does the ARM distro you are using have nasm?

**Comment by stsp** [comment]
Please use `XAS`, `AS_LD` and
`XOBJCOPY` for cross-tools.
As for gcc - I suppose its for producing
the reference output for cpu tests?
Could you please instead add the
pre-generated "good" results?

**Comment by stsp** [comment]
> Does the ARM distro you are using have nasm?

Sure thing, I use ubuntu.
The only deficiency I've noticed so
far is that under gdb, once you hit a
break-point, you can't continue until
you disable that break-point. Strange
that they live with such a bug.

**Comment by stsp** [comment]
fdpp also uses nasm, so of course
we have nasm. Our PPA now contains
all arm builds.

**Comment by andrewbird** [comment]
> Sure thing, I use ubuntu.

What's your hardware?

**Comment by stsp** [comment]
```
qemu-system-aarch64 -m 1G -cpu cortex-a57 -M virt \
    -pflash flash0.img -pflash flash1.img \
    -drive if=none,file=kinetic-server-cloudimg-arm64.img,id=hd0 \
    -device virtio-blk-device,drive=hd0 \
    -drive file=user-data.img,format=raw \
    -netdev type=user,id=net0 -device virtio-net-device,netdev=net0 \
    -monitor none \
    -smp 6
```

**Comment by andrewbird** [comment]
Interesting, I thought you might have a Raspberry Pi or something. I have some really old ones (the first revision), and one 3b+ which is in use for something else. Just waiting for the current price stupidity to subside, then perhaps I'll get a 4.

**Comment by stsp** [comment]
I had various arm boards from work,
but with the famous recent events I have
none and enough free time for dosemu2
coding. :)

**Comment by stsp** [comment]
Btw Bart, could you please provide
a bit of a road-map for inclusion of the
tcg? While in dosemu1 times such a
road-map would be just "you need to
rewrite entire dosemu", currently I
expect something else.
Isn't our core modular and simple
enough to just try including it as yet
another back-end?

**Comment by stsp** [comment]
> a lack of djgpp and ia16gcc for ARM is a bigger problem.

Another possible solution here
is to package tests separately of
dosemu2. But I admit it has an
obvious down-sides.
