### ISSUE TITLE
Packet Driver: statistics implausible

### ISSUE THREAD

**Issue by robert-j** [dosemu2/dosemu2#2008]
**Describe the bug**
The Packet Driver function 24 (F_GET_STATS) should return a ptr to a struct with the following layout:

```
#pragma pack(push, 1)
typedef struct {
    uint32_t packets_in;    /* Totals across all handles */
    uint32_t packets_out;
    uint32_t bytes_in;      /* Including MAC headers */
    uint32_t bytes_out;
    uint32_t errors_in;     /* Totals across all error types */
    uint32_t errors_out;
    uint32_t packets_lost;  /* No buffer from receiver(), out of resources, etc. */
} pd_stats_t;
#pragma pack(pop)
```

dosemu2's Packet Driver is supporting this function but the returned values are incorrect.

This is how dosemu2 is [defining](https://github.com/dosemu2/dosemu2/blob/devel/src/include/pktdrvr.h#L75) the struct.
This looks good up to the fact that on 64 bit platforms the layout obviously doesn't match the Packet Driver specification ;)

Its usage in [pktnew.c](https://github.com/dosemu2/dosemu2/blob/devel/src/dosext/net/pktnew.c) makes me believe that the DOS client is receiving a pointer to a 64 bit struct.

What I get from dosemu2 is:

```
Packets in ...... 71165
Packets out ..... 0
Bytes in ........ 35244
Bytes out ....... 0
Errors in ....... 90067435
Errors out ...... 0
Packets lost .... 32192759
```

which is totally wrong. Since "Packets in" is plausible, this is most likely a 64bit structure.

Hex dump of the stats:

```
Dump 28 Bytes
0000  fd 15 01 00 00 00 00 00  ac 89 00 00 00 00 00 00  ................ 
0010  eb 51 5e 05 00 00 00 00  f7 38 eb 01              .Q^......8..     
```

**Comment by stsp** [comment]
Would you like to provide a pull request
with the tested fix?

**Comment by stsp** [comment]
You need to use `__attribute__((packed))`
instead of a pragma.

**Comment by robert-j** [comment]
This was my struct (on the client side) for which I used the MS kind of packing. But sure, I can provide a fix for dosemu2, too.

**Comment by andrewbird** [comment]
Results from mTCP's pkttool look better
~~~
C:\>pkttool stats 0x60
 
mTCP pkttool by M Brutman (mbbrutman@gmail.com) (C)opyright 2012-2022
Version: Jul  1 2022
 
Details for driver at software interrupt: 0x60
  Name: Linux$
  Entry point: F000:F57A
  Version: 1   Class: 1   Type: 12  Interface Number: 1
  Function flag: 2  (basic and extended functions)
  Current receive mode: all packets (promiscuous mode)
  MAC address: 66:62:78:B3:5F:54
 
All statistics are from when the packet driver was loaded.
 
Packets in:           10  Packets received
Packets out:           5  Packets sent
Bytes in:           1166  Bytes received (includes Ethernet headers)
Bytes out:           797  Bytes sent (includes Ethernet headers)
Errors in:             0  Receive errors
Errors out:            0  Sending errors
Packets lost:          0  Lost due to no packet handler, out of buffers, etc.
~~~
