### ISSUE TITLE
Compile on freebsd: add "#include <fcntl.h>" to dosemu2-devel/src/base/lib/timer/evtimer_fd.c

### ISSUE THREAD

**Issue by daneli1** [dosemu2/dosemu2#2118]
Thanks for your work bringing dosemu2 to freebsd! I couldn't compile on freeBSD successfully until I added an "#include <fcntl.h>" to dosemu2-devel/src/base/lib/timer/evtimer_fd.c. Thought you might want to add this change yourself. Thanks again.

**Comment by stsp** [comment]
Wow!
Indeed, FreeBSD seems to have
adopted timerfd recently:
https://www.mail-archive.com/dev-commits-src-all@freebsd.org/msg43447.html
This is the good step, because, unlike
that mail claims, posix APIs are broken
(posix timers are completely broken for
sure).
So yes, lets add such include.
Note that I am not really sure if fdpp
can still be built on freebsd. It would
be really good if you re-check that,
because I think right now fdpp is not
portable again, for a moment.
