### ISSUE TITLE
cpu_vm_dpmi mode "native" seems a bit broken

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#2150]
**Describe the bug**
I get an "DPMI: unhandled exception 0e - Terminating client" in DPMI native mode when I run the small testcase attached. If I select "KVM mode", the program runs without exception.

**To Reproduce**
run the testcase attached ( hello.exe ). Nothing should be displayed.

[hello.zip](https://github.com/dosemu2/dosemu2/files/14318292/hello.zip)

**Comment by stsp** [comment]
Thanks, good catch!
I wonder why didn't that trigger before.

**Comment by Baron-von-Riedesel** [comment]
> I wonder why didn't that trigger before.

Perhaps because nobody is able to create DosEmu+Fdpp anymore?

**Comment by stsp** [comment]
But its in ppa, so why should the
one build it. :)

**Comment by stsp** [comment]
In fact I do realize that dosemu2+fdpp
became a very challenging combo to
build, and I actually tried very hard to
change that trend.

I talked to nasm devs, but failed to
convince them to even look into a
segelf patch. So the nasm-segelf fork.
I talked to gcc devs but failed to convince
them to at least fix the most obvious
bugs so that fdpp can be built, not
speaking about the full fdpp support.
Hence clang - its devs are very supportive.

I talked to C++ standard writers, but as
the result, they rephrased the standard
to disable the features I used... Fortunately
the clang dev came to the rescue and
gave me the convoluted trick with lambdas,
for which I had to raise the standard version
to c++-20, further troubling the builds.

binutils project is very supportive, all the
needed patches are in (or work-arounds
are provided to me), so at least no problems
with latest binutils. I wish other project be
that good, but they are not.

Hope that clarifies the current situation
with the assorted set of tools needed to
build fdpp. But now we have meson, which
has the proper configuration process and
is supposed to tell you what is missing or
incompatible. Unfortunately it turned out
that fdpp can be built only with meson-1.3,
which is not available in most distros yet...
It will only be available in upcoming distros,
like fedora-40 and ubuntu-24.04, so I expect
the trouble-free fdpp build at least there.
But if you try to build dosemu2 on a less
popular distros like eg Alpine - that's a
complete dead end, so we can only support
the most popular distros.
Unfortunately I failed to build comcom64
with meson even after submitting the needed
patches to them, so meson also doesn't put
us off of this hook even on good distros.

Since everything seems to fail, my new
strategy will be based around the pre-built
setups. If we build into AppImage and FlatPack,
and promote dosemu2+fdpp to the popular
distros, then maybe people will stop building
by hands? But that strategy is also not without
troubles. For example, one needs to get rid
of djgpp, as its not available in distros, but is
used to build comcom32... And you probably
already know the story around comcom64.

So... Let's say that the solution for this building
problem is yet to be found. If you have one,
please speak up. :)
