### ISSUE TITLE
Sorcerian doesn't run (mt32)

### ISSUE THREAD

**Issue by ghost** [dosemu2/dosemu2#543]
Sorcerian doesn't run.  This game is based on the same engine as Zeliard, which runs now, but didn't just a few months ago.

http://home.ix.netcom.com/~jjingber/sorc.tar.bz2
http://home.ix.netcom.com/~jjingber/boot.log.tar.bz2

**Comment by jharrison022** [comment]
Maybe problem with MIDI.

**Comment by jharrison022** [comment]
Works with Adlib.  Bombs with MT-32.

**Comment by stsp** [comment]
We do not support mt32 well.
Try GM or GS.
`sound.com` utility can be used to
switch the synth mode.

**Comment by runderwo** [comment]
This is another intelligent mode title.  https://github.com/bjt42/softmpu/wiki/Compatible-Intelligent-Mode-Games

For now, you can try to replace the MT32.DRV with the one from Zeliard (that works), since the reason it works is probably that it's using the simpler MPU-401 UART mode.

**Comment by stsp** [comment]
Yes, the last time ticket #117 was opened,
we got UART mode to work with munt.
To the date its still all we have.
Ryan, how goes your mt32 code? :)

**Comment by runderwo** [comment]
@stsp It's the same as it was - it works, but the timing issues are annoying.  We can hack on it together in the next few weeks if you have the time and are on skype or something similar.  I thought you were not that interested before for some reason :)

**Comment by stsp** [comment]
Back then I was interested to create some
solid ground for mt32, namely, the munt plugin
and sound.com utility. And that's what I did.
You also fixed munt on alsa, so that part was
fully completed.
i don't need to be interested in the code you
write, as otherwise I would write it myself instead. :)
But I am very interested to take another look
into the timing problem you had.
So please describe it again.

**Comment by runderwo** [comment]
I am not interested in the code I write either.  I am interested in adding features that I miss to dosemu.

I haven't looked at it for some time, but as I recall, the timing problem is that unless the dosemu window is interacted with (via keyboard or mouse), the music track slows down, probably because the program itself is running more slowly.  I thought it was related to hogthreshold, but disabling it didn't make a difference.

**Comment by stsp** [comment]
IIRC you did some work-around with signal.

**Comment by jharrison022** [comment]
<quote>This is another intelligent mode title. https://github.com/bjt42/softmpu/wiki/Compatible-Intelligent-Mode-Games></quote>

Most of those games actually do work just fine with the current code.

**Comment by stsp** [comment]
Please see #45 for an explanation.
I added the hack that always forces an
UART mode. This works quite fine because
even in intelligent mode the games just
tell the hardware (by writing d0 to command
port or by other means) to please send the
midi data, so the things work.
It seems #45 concludes that games marked
with `(1)` will not currently work, the rest will.

**Comment by runderwo** [comment]
@jharrison It completely depends on what the driver does.  If it's setting WSD and then streaming data to the device, ignoring the non-UART commands works fine.  If it's using interrupts and/or the hardware sequencer, there's no way it will work.  There are multiple Sierra MT-32 drivers; the older ones will not work with a pure UART, but the newer one will, and they are often interchangeable.

**Comment by stsp** [comment]
@runderwo by the way if you haven't
tested your code since, you may not be
sure there is still the timing problem which
you had to work-around with signals...
Maybe its not there? :)

**Comment by runderwo** [comment]
@stsp I'll try it again, but IIRC you didn't like the approach and preferred getting the SoftMPU TSR to work instead.  (Which is fine with me and reduces code repetition, except I'm probably the wrong person to do that - emulating the necessary EMM386 hooks is not at all something I'm familiar with.)

**Comment by jharrison022** [comment]
Swapping the MT32.DRV from Zeliard into Sorcerian does work.  IIRC, there was a 100+ post thread regarding Silpheed which ended in a similar fix (ie. swapping the Sierra MT32.DRV from a different version into the "broken" one).

**Comment by runderwo** [comment]
@jharrison022 Though that one was different, it was a bug in Munt exposed by the PS/1 Silpheed MT32 driver.  That driver still worked with UART emulation, but sent pathologically long sysexes that overflowed an internal buffer.

**Comment by stsp** [comment]
> @stsp I'll try it again, but IIRC you didn't like the approach

Because it was implemented in a wrong place
(dspio.c IIRC).

> and preferred getting the SoftMPU TSR to work instead.

This can be done too, but we already have
`sound.com` that sets mt32 mode, so builtin
support is good too. Its just that it doesn't
belong to sb16 - I think `sound.com` should
choose whether sb16.c processes mpu401
internally or passes to the "daughter board".

**Comment by stsp** [comment]
> That driver still worked with UART emulation, but sent
> pathologically long sysexes that overflowed an internal buffer.

Interestingly, I had to apply the similar fix
to fluidsynth to allow dosemu2 to record the
silpheed music to midi file. It was also truncating
the sysexes.

**Comment by stsp** [comment]
This should now be fixed.
Let me know if not.

**Comment by andrewbird** [comment]
Or is a ghost, so you are unlikely to get a reply

**Comment by stsp** [comment]
The fact is, mt32 was implemented, thanks to @jharrison03 funding of it. :)
So I dont care the ghosts.

Понедельник, 23 декабря 2024 г получено от Andrew Bird:
